// apps/desktop/src/features/jobs/views/JobDetailView.tsx
import { message } from "@tauri-apps/plugin-dialog";
import { useEffect, useMemo, useState } from "react";
import { Link, useRouter } from "@/app/router/RouterContext";
import StatusBadge from "@/shared/components/StatusBadge";
import { useMeetingStore } from "@/features/meeting/stores/useMeetingStore";
import { getMessages } from "@/shared/i18n";
import progressBarUrl from "@/assets/progress-bar.webp";
import type { JobStage } from "@/shared/types/meeting";

const ansiPattern = /\u001b\[[0-9;]*m/g;
const stageProgressBands: Record<JobStage, { min: number; max: number }> = {
  idle: { min: 0, max: 0 },
  uploaded: { min: 4, max: 8 },
  queued: { min: 8, max: 14 },
  transcribing: { min: 18, max: 72 },
  speaker_processing: { min: 72, max: 96 },
  summarizing: { min: 96, max: 99 },
  completed: { min: 100, max: 100 },
  failed: { min: 0, max: 99 },
};

export default function JobDetailView() {
  const router = useRouter();
  const store = useMeetingStore();
  const jobId = router.params.id ?? "";
  const job = store.getJobById(jobId);
  const messages = getMessages(store.settings.locale).jobDetail;
  const commonMessages = getMessages(store.settings.locale).common;
  const statusMessages = getMessages(store.settings.locale).status;
  const shouldWarnModelDownloadRequired = !store.settings.backendUrl.trim() && store.runtimeStatus.status !== "ready";
  const [displayProgressPercent, setDisplayProgressPercent] = useState(0);
  const [progressRunKey, setProgressRunKey] = useState("");
  const stages = job
    ? [
        { label: messages.stageUploaded, status: job.uploadStatus },
        { label: messages.stageAsr, status: job.asrStatus },
        { label: messages.stageSummary, status: job.summaryStatus },
        { label: messages.stageOverall, status: job.overallStatus },
      ]
    : [];

  useEffect(() => {
    if (jobId) {
      void store.refreshJob(jobId);
    }
  }, [jobId]);

  function clampPercent(value: number, min: number, max: number) {
    return Math.max(min, Math.min(max, Math.round(value)));
  }

  function getProgressStage() {
    if (!job) {
      return "idle" as JobStage;
    }

    if (job.overallStatus !== "idle") {
      return job.overallStatus;
    }

    if (job.summaryStatus !== "idle") {
      return job.summaryStatus;
    }

    if (job.asrStatus !== "idle") {
      return job.asrStatus;
    }

    return job.uploadStatus;
  }

  function resolveStageProgressPercent() {
    const stage = getProgressStage();
    const rawPercent = job?.progressPercent;

    if (stage === "completed") {
      return 100;
    }

    if (typeof rawPercent !== "number" || Number.isNaN(rawPercent)) {
      return stageProgressBands[stage].min;
    }

    if (stage === "failed") {
      return clampPercent(rawPercent, 0, 99);
    }

    const { min, max } = stageProgressBands[stage];
    return clampPercent(rawPercent, min, max);
  }

  useEffect(() => {
    if (!job) {
      setDisplayProgressPercent(0);
      setProgressRunKey("");
      return;
    }

    const runKey = `${job.id}:${job.processingStartedAtMs ?? 0}`;
    const nextPercent = resolveStageProgressPercent();

    if (progressRunKey !== runKey) {
      setProgressRunKey(runKey);
      setDisplayProgressPercent(nextPercent);
      return;
    }

    setDisplayProgressPercent((current) => Math.max(current, nextPercent));
  }, [job?.id, job?.processingStartedAtMs, job?.overallStatus, job?.summaryStatus, job?.asrStatus, job?.uploadStatus, job?.progressPercent]);

  const progressMessage = useMemo(() => {
    if (!job) {
      return "";
    }

    const explicit = job.progressMessage?.trim();
    if (explicit) {
      return explicit;
    }

    return statusMessages[job.overallStatus as keyof typeof statusMessages] ?? job.overallStatus;
  }, [job, statusMessages]);

  const logEntries = useMemo(() => {
    const raw = job?.processLog ?? "";
    return raw
      .split(/[\r\n]+/)
      .map((line) => line.replace(ansiPattern, "").trim())
      .filter((line) => line.length > 0)
      .reverse()
      .map((line, index) => ({
        id: `${index}-${line.slice(0, 24)}`,
        text: line,
        tone: classifyLogLine(line),
      }));
  }, [job?.processLog]);

  function classifyLogLine(line: string) {
    const normalized = line.toLowerCase();
    if (
      normalized.includes("traceback")
      || normalized.includes("permissionerror")
      || normalized.includes("runtimeerror")
      || normalized.includes("error")
      || normalized.includes("failed")
      || normalized.includes("失败")
    ) {
      return "error";
    }

    if (normalized.includes("warning") || normalized.includes("warn")) {
      return "warning";
    }

    if (
      normalized.includes("completed")
      || normalized.includes("success")
      || normalized.includes("已完成")
      || normalized.includes("完成")
    ) {
      return "success";
    }

    return "info";
  }

  async function retryJob(targetJobId: string) {
    if (shouldWarnModelDownloadRequired) {
      await message(commonMessages.modelUnavailableMessage, {
        title: commonMessages.modelUnavailableTitle,
        kind: "warning",
      });
      return;
    }

    await store.retryJob(targetJobId);
  }

  return (
    <section className="view-stack native-page detail-native-page">
      {job ? (
        <div className="detail-grid">
          <article className="surface native-page-hero detail-hero full-span">
            <div className="job-title-line detail-hero-head">
              <div className="native-title-stack">
                <Link className="text-button small-button native-back-link" to="/jobs">
                  {messages.backToJobs}
                </Link>
                <div>
                  <h3>{job.title}</h3>
                  <p className="section-copy">{job.sourceFiles.map((file) => file.name).join(" · ")}</p>
                </div>
              </div>
              <StatusBadge status={job.overallStatus} />
            </div>

            <div className="detail-stage-grid">
              {stages.map((stage) => (
                <div key={stage.label} className="detail-stage-card">
                  <span className="detail-stage-label">{stage.label}</span>
                  <StatusBadge status={stage.status} />
                </div>
              ))}
            </div>

            <div className="detail-hero-footer">
              <div className="summary-inline">
                <span>{messages.inputFiles} {job.sourceFiles.length}</span>
                <span>{messages.hotwords} {job.hotwords.length}</span>
                <span>{messages.speaker} {job.enableSpeaker ? commonMessages.enabled : commonMessages.disabled}</span>
              </div>

              <div className="button-row">
                {job.overallStatus === "completed" && (
                  <Link className="primary-button" to={`/jobs/${job.id}/workbench`}>
                    {messages.viewWorkbench}
                  </Link>
                )}
                {job.overallStatus === "failed" && (
                  <button className="secondary-button" type="button" onClick={() => retryJob(job.id)}>
                    {messages.retryJob}
                  </button>
                )}
              </div>
            </div>
          </article>

          <article className="surface native-info-panel detail-main-column">
            <div className="section-heading">
              <h3>{messages.filesSection}</h3>
            </div>
            <div className="file-list">
              {job.sourceFiles.map((file) => (
                <div key={file.id} className="file-pill">
                  <div>
                    <strong>{file.name}</strong>
                    <div className="job-meta-line">
                      {file.kind === "audio" ? commonMessages.audio : commonMessages.video} · {file.sizeLabel}
                    </div>
                  </div>
                </div>
              ))}
            </div>
          </article>

          <article className="surface native-info-panel detail-side-column">
            <div className="section-heading">
              <h3>{messages.settingsSection}</h3>
            </div>
            <div className="metric-strip metric-strip-tight">
              <div className="metric-pill">
                <span className="muted">{messages.language}</span>
                <strong>{job.lang}</strong>
              </div>
              <div className="metric-pill">
                <span className="muted">{messages.speakerDiarization}</span>
                <strong>{job.enableSpeaker ? commonMessages.enabled : commonMessages.disabled}</strong>
              </div>
              <div className="metric-pill">
                <span className="muted">{messages.hotwords}</span>
                <strong>{job.hotwords.length}</strong>
              </div>
            </div>
          </article>

          <article className="surface native-info-panel detail-progress-card full-span">
            <div className="section-heading">
              <h3>{messages.progressSection}</h3>
              <strong className="detail-progress-percent">{displayProgressPercent}%</strong>
            </div>

            <div className="detail-progress-panel">
              <div className="detail-progress-meta">
                <span className="detail-progress-label">{messages.stageOverall}</span>
                <StatusBadge status={job.overallStatus} />
              </div>
              <div className="detail-progress-track">
                <div className="detail-progress-fill" style={{ width: `${displayProgressPercent}%` }}>
                  <img className="detail-progress-media" src={progressBarUrl} alt="" aria-hidden="true" />
                </div>
              </div>
              <p className="section-copy detail-progress-copy">{progressMessage}</p>
            </div>
          </article>

          <article className="surface native-info-panel detail-log-card full-span">
            <div className="section-heading">
              <h3>{messages.logSection}</h3>
            </div>
            {job.failureReason && <div className="note-block error-block">{job.failureReason}</div>}
            {logEntries.length ? (
              <div className="job-log-list">
                {logEntries.map((entry) => (
                  <div key={entry.id} className={`job-log-entry job-log-entry-${entry.tone}`}>
                    {entry.text}
                  </div>
                ))}
              </div>
            ) : (
              <div className="empty-state">{messages.noLog}</div>
            )}
          </article>
        </div>
      ) : (
        <div className="empty-state">{messages.notFound}</div>
      )}
    </section>
  );
}

// src/views/JobDetailView.vue
<script setup lang="ts">
import { computed, ref, watch } from "vue";
import { RouterLink, useRoute } from "vue-router";
import StatusBadge from "@/components/StatusBadge.vue";
import { useMeetingStore } from "@/composables/useMeetingStore";
import { getMessages } from "@/services/i18n";
import progressBarUrl from "@/assets/progress-bar.webp";
import type { JobStage } from "@/types/meeting";

const route = useRoute();
const store = useMeetingStore();
const messages = computed(() => getMessages(store.settings.value.locale).jobDetail);
const commonMessages = computed(() => getMessages(store.settings.value.locale).common);
const statusMessages = computed(() => getMessages(store.settings.value.locale).status);

const job = computed(() => store.getJobById(route.params.id as string));

const ansiPattern = /\u001b\[[0-9;]*m/g;

const stages = computed(() => {
  if (!job.value) {
    return [];
  }

  return [
    { label: messages.value.stageUploaded, status: job.value.uploadStatus },
    { label: messages.value.stageAsr, status: job.value.asrStatus },
    { label: messages.value.stageSummary, status: job.value.summaryStatus },
    { label: messages.value.stageOverall, status: job.value.overallStatus },
  ];
});

const displayProgressPercent = ref(0);
const progressRunKey = ref("");

const stageProgressBands: Record<JobStage, { min: number; max: number }> = {
  idle: { min: 0, max: 0 },
  uploaded: { min: 4, max: 8 },
  queued: { min: 8, max: 14 },
  transcribing: { min: 18, max: 72 },
  speaker_processing: { min: 72, max: 96 },
  summarizing: { min: 96, max: 99 },
  completed: { min: 100, max: 100 },
  failed: { min: 0, max: 99 },
};

function clampPercent(value: number, min: number, max: number) {
  return Math.max(min, Math.min(max, Math.round(value)));
}

function getProgressStage() {
  if (!job.value) {
    return "idle" as JobStage;
  }

  if (job.value.overallStatus !== "idle") {
    return job.value.overallStatus as JobStage;
  }

  if (job.value.summaryStatus !== "idle") {
    return job.value.summaryStatus as JobStage;
  }

  if (job.value.asrStatus !== "idle") {
    return job.value.asrStatus as JobStage;
  }

  return job.value.uploadStatus as JobStage;
}

function resolveStageProgressPercent() {
  const stage = getProgressStage();
  const rawPercent = job.value?.progressPercent;

  if (stage === "completed") {
    return 100;
  }

  if (typeof rawPercent !== "number" || Number.isNaN(rawPercent)) {
    return stageProgressBands[stage].min;
  }

  if (stage === "failed") {
    return clampPercent(rawPercent, 0, 99);
  }

  const { min, max } = stageProgressBands[stage];
  return clampPercent(rawPercent, min, max);
}

const progressPercent = computed(() => displayProgressPercent.value);

watch(
  () => ({
    jobId: job.value?.id ?? "",
    runKey: `${job.value?.id ?? ""}:${job.value?.processingStartedAtMs ?? 0}`,
    stage: getProgressStage(),
    rawPercent: job.value?.progressPercent ?? null,
  }),
  ({ jobId, runKey }) => {
    if (!jobId) {
      displayProgressPercent.value = 0;
      progressRunKey.value = "";
      return;
    }

    const nextPercent = resolveStageProgressPercent();

    if (progressRunKey.value !== runKey) {
      progressRunKey.value = runKey;
      displayProgressPercent.value = nextPercent;
      return;
    }

    displayProgressPercent.value = Math.max(displayProgressPercent.value, nextPercent);
  },
  { immediate: true },
);

const progressMessage = computed(() => {
  if (!job.value) {
    return "";
  }

  const explicit = job.value.progressMessage?.trim();
  if (explicit) {
    return explicit;
  }

  return (
    statusMessages.value[job.value.overallStatus as keyof typeof statusMessages.value] ?? job.value.overallStatus
  );
});

const logEntries = computed(() => {
  const raw = job.value?.processLog ?? "";
  return raw
    .split(/[\r\n]+/)
    .map((line) => line.replace(ansiPattern, "").trim())
    .filter((line) => line.length > 0)
    .reverse()
    .map((line, index) => ({
      id: `${index}-${line.slice(0, 24)}`,
      text: line,
      tone: classifyLogLine(line),
    }));
});

function classifyLogLine(line: string) {
  const normalized = line.toLowerCase();
  if (
    normalized.includes("traceback")
    || normalized.includes("permissionerror")
    || normalized.includes("runtimeerror")
    || normalized.includes("error")
    || normalized.includes("failed")
    || normalized.includes("失败")
  ) {
    return "error";
  }

  if (normalized.includes("warning") || normalized.includes("warn")) {
    return "warning";
  }

  if (
    normalized.includes("completed")
    || normalized.includes("success")
    || normalized.includes("已完成")
    || normalized.includes("完成")
  ) {
    return "success";
  }

  return "info";
}
</script>

<template>
  <section class="view-stack">
    <div v-if="job" class="detail-grid">
      <article class="surface detail-hero full-span">
        <div class="job-title-line detail-hero-head">
          <div>
            <h3>{{ job.title }}</h3>
            <p class="section-copy">
              {{ job.sourceFiles.map((file) => file.name).join(" · ") }}
            </p>
          </div>
          <StatusBadge :status="job.overallStatus" />
        </div>

        <div class="detail-stage-grid">
          <div v-for="stage in stages" :key="stage.label" class="detail-stage-card">
            <span class="detail-stage-label">{{ stage.label }}</span>
            <StatusBadge :status="stage.status" />
          </div>
        </div>

        <div class="detail-hero-footer">
          <div class="summary-inline">
            <span>{{ messages.inputFiles }} {{ job.sourceFiles.length }}</span>
            <span>{{ messages.hotwords }} {{ job.hotwords.length }}</span>
            <span>{{ messages.speaker }} {{ job.enableSpeaker ? commonMessages.enabled : commonMessages.disabled }}</span>
          </div>

          <div class="button-row">
            <RouterLink
              v-if="job.overallStatus === 'completed'"
              class="primary-button"
              :to="`/jobs/${job.id}/workbench`"
            >
              {{ messages.viewWorkbench }}
            </RouterLink>
            <button
              v-if="job.overallStatus === 'failed'"
              class="secondary-button"
              type="button"
              @click="store.retryJob(job.id)"
            >
              {{ messages.retryJob }}
            </button>
          </div>
        </div>
      </article>

      <article class="surface detail-main-column">
        <div class="section-heading">
          <h3>{{ messages.filesSection }}</h3>
        </div>
        <div class="file-list">
          <div v-for="file in job.sourceFiles" :key="file.id" class="file-pill">
            <div>
              <strong>{{ file.name }}</strong>
              <div class="job-meta-line">
                {{ file.kind === "audio" ? commonMessages.audio : commonMessages.video }} · {{ file.sizeLabel }}
              </div>
            </div>
          </div>
        </div>
      </article>

      <article class="surface detail-side-column">
        <div class="section-heading">
          <h3>{{ messages.settingsSection }}</h3>
        </div>
        <div class="metric-strip metric-strip-tight">
          <div class="metric-pill">
            <span class="muted">{{ messages.language }}</span>
            <strong>{{ job.lang }}</strong>
          </div>
          <div class="metric-pill">
            <span class="muted">{{ messages.speakerDiarization }}</span>
            <strong>{{ job.enableSpeaker ? commonMessages.enabled : commonMessages.disabled }}</strong>
          </div>
          <div class="metric-pill">
            <span class="muted">{{ messages.hotwords }}</span>
            <strong>{{ job.hotwords.length }}</strong>
          </div>
        </div>
      </article>

      <article class="surface detail-progress-card full-span">
        <div class="section-heading">
          <h3>{{ messages.progressSection }}</h3>
          <strong class="detail-progress-percent">{{ progressPercent }}%</strong>
        </div>

        <div class="detail-progress-panel">
          <div class="detail-progress-meta">
            <span class="detail-progress-label">{{ messages.stageOverall }}</span>
            <StatusBadge :status="job.overallStatus" />
          </div>
          <div class="detail-progress-track">
            <div class="detail-progress-fill" :style="{ width: `${progressPercent}%` }">
              <img class="detail-progress-media" :src="progressBarUrl" alt="" aria-hidden="true" />
            </div>
          </div>
          <p class="section-copy detail-progress-copy">
            {{ progressMessage }}
          </p>
        </div>
      </article>

      <article class="surface detail-log-card full-span">
        <div class="section-heading">
          <h3>{{ messages.logSection }}</h3>
        </div>
        <div v-if="job.failureReason" class="note-block error-block">
          {{ job.failureReason }}
        </div>
        <div v-if="logEntries.length" class="job-log-list">
          <div
            v-for="entry in logEntries"
            :key="entry.id"
            class="job-log-entry"
            :class="`job-log-entry-${entry.tone}`"
          >
            {{ entry.text }}
          </div>
        </div>
        <div v-else class="empty-state">
          {{ messages.noLog }}
        </div>
      </article>
    </div>

    <div v-else class="empty-state">
      {{ messages.notFound }}
    </div>
  </section>
</template>
