// apps/desktop/src/features/jobs/views/NewJobView.tsx
import { message, open } from "@tauri-apps/plugin-dialog";
import { useEffect, useRef, useState } from "react";
import { useRouter } from "@/app/router/RouterContext";
import { useMeetingStore } from "@/features/meeting/stores/useMeetingStore";
import { formatMessage, getMessages } from "@/shared/i18n";
import type { MeetingSourceFile } from "@/shared/types/meeting";

export default function NewJobView() {
  const router = useRouter();
  const store = useMeetingStore();
  const [title, setTitle] = useState("");
  const [hotwordsText, setHotwordsText] = useState(store.settings.defaultHotwords);
  const [previousDefaultHotwords, setPreviousDefaultHotwords] = useState(store.settings.defaultHotwords);
  const [lang, setLang] = useState("zh-CN");
  const [enableSpeaker, setEnableSpeaker] = useState(true);
  const [files, setFiles] = useState<MeetingSourceFile[]>([]);
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [submitError, setSubmitError] = useState("");
  const fileInput = useRef<HTMLInputElement | null>(null);
  const isLocalMode = store.localMode;
  const messages = getMessages(store.settings.locale).newJob;
  const commonMessages = getMessages(store.settings.locale).common;
  const jobsMessages = getMessages(store.settings.locale).jobs;
  const summaryTemplate = store.settings.summaryTemplate.trim() || messages.defaultSummaryTemplateName;
  const shouldWarnModelDownloadRequired = !store.settings.backendUrl.trim() && store.runtimeStatus.status !== "ready";
  const serviceModeLabel = store.localMode
    ? messages.localPython
    : store.settings.backendUrl.trim()
      ? messages.remoteService
      : messages.envMissing;
  const recentJobs = store.jobs.slice(0, 4);
  const activeJobs = store.jobs.filter((job) =>
    ["queued", "transcribing", "speaker_processing", "summarizing"].includes(job.overallStatus),
  ).length;
  const failedJobs = store.jobs.filter((job) => job.overallStatus === "failed").length;

  useEffect(() => {
    if (!hotwordsText.trim() || hotwordsText === previousDefaultHotwords) {
      setHotwordsText(store.settings.defaultHotwords);
    }
    setPreviousDefaultHotwords(store.settings.defaultHotwords);
  }, [store.settings.defaultHotwords]);

  function inferKind(fileName: string): "audio" | "video" {
    return /\.(mp4|mov|mkv)$/i.test(fileName) ? "video" : "audio";
  }

  function humanSize(size?: number) {
    if (!size) {
      return commonMessages.unknownSize;
    }

    const mb = size / 1024 / 1024;
    return `${mb.toFixed(1)} MB`;
  }

  function fileNameToTitle(fileName: string) {
    return fileName.replace(/\.[^.]+$/, "").trim();
  }

  function fileToSource(file: File): MeetingSourceFile {
    return {
      id: crypto.randomUUID(),
      name: file.name,
      sizeLabel: humanSize(file.size),
      kind: inferKind(file.name),
    };
  }

  function addFiles(next: MeetingSourceFile[]) {
    const lastFile = next.at(-1);

    if (isLocalMode) {
      setFiles((current) => (lastFile ? [lastFile] : current));
      if (!title.trim() && lastFile) {
        setTitle(fileNameToTitle(lastFile.name));
      }
      return;
    }

    setFiles((current) => [...current, ...next]);

    if (!title.trim() && lastFile) {
      setTitle(fileNameToTitle(lastFile.name));
    }
  }

  async function pickFiles() {
    try {
      const selected = await open({
        multiple: !isLocalMode,
        directory: false,
        filters: [
          {
            name: "Meeting Media",
            extensions: ["m4a", "mp3", "wav", "aac", "flac", "mp4", "mov", "mkv"],
          },
        ],
      });

      if (!selected) {
        return;
      }

      const normalized = Array.isArray(selected) ? selected : [selected];

      addFiles(
        normalized.map((path) => {
          const name = path.split("/").pop() ?? path;

          return {
            id: crypto.randomUUID(),
            name,
            path,
            sizeLabel: commonMessages.localPath,
            kind: inferKind(name),
          } satisfies MeetingSourceFile;
        }),
      );
    } catch {
      fileInput.current?.click();
    }
  }

  function onNativeFileChange(event: React.ChangeEvent<HTMLInputElement>) {
    const selected = Array.from(event.target.files ?? []).map(fileToSource);
    addFiles(selected);
    event.target.value = "";
  }

  function removeFile(id: string) {
    setFiles((current) => current.filter((file) => file.id !== id));
  }

  async function submit() {
    setSubmitError("");

    if (!files.length || !title.trim()) {
      return;
    }

    if (shouldWarnModelDownloadRequired) {
      await message(commonMessages.modelUnavailableMessage, {
        title: commonMessages.modelUnavailableTitle,
        kind: "warning",
      });
      return;
    }

    if (isLocalMode && files.some((file) => !file.path)) {
      setSubmitError(messages.localPathRequired);
      return;
    }

    setIsSubmitting(true);

    try {
      const job = await store.createJob({
        title: title.trim(),
        files,
        hotwords: hotwordsText
          .split(",")
          .map((item) => item.trim())
          .filter(Boolean),
        lang,
        enableSpeaker,
        summaryTemplate,
      });

      await router.push(`/jobs/${job.id}`);
    } catch (error) {
      setSubmitError(error instanceof Error ? error.message : messages.createFailed);
    } finally {
      setIsSubmitting(false);
    }
  }

  return (
    <section className="new-job-native-page">
      <input
        ref={fileInput}
        type="file"
        accept=".m4a,.mp3,.wav,.aac,.flac,.mp4,.mov,.mkv"
        multiple={!isLocalMode}
        hidden
        onChange={onNativeFileChange}
      />

      <div className="new-job-workspace">
        <main className="new-job-composer">
          <header className="new-job-page-head">
            <div>
              <p className="new-job-kicker">{serviceModeLabel}</p>
              <h2>{messages.heroTitle}</h2>
              <p>{messages.heroCopy}</p>
            </div>
            <button className="secondary-button" type="button" onClick={pickFiles}>
              {files.length ? (isLocalMode ? messages.reselect : messages.continueAdding) : messages.addFiles}
            </button>
          </header>

          <article className="new-job-sheet">
            <div className="field new-job-title-field">
              <label htmlFor="job-title">{messages.jobTitle}</label>
              <input id="job-title" value={title} onChange={(event) => setTitle(event.target.value)} placeholder={messages.titlePlaceholder} />
            </div>

            <section className="new-job-section">
              <div className="new-job-section-head">
                <div>
                  <h3>{messages.inputFiles}</h3>
                  <p>{isLocalMode ? messages.desktopFilePicker : messages.mediaSupported}</p>
                </div>
                {files.length > 0 && (
                  <button className="text-button danger-text" type="button" onClick={() => setFiles([])}>
                    {messages.clearList}
                  </button>
                )}
              </div>

              <div className={`drop-zone new-job-file-box ${files.length ? "has-files" : ""}`}>
                {!files.length ? (
                  <button className="drop-zone-button" type="button" onClick={pickFiles}>
                    <div className="drop-zone-copy">
                      <strong>{messages.addFiles}</strong>
                      <p>{isLocalMode ? messages.desktopFilePicker : messages.mediaSupported}</p>
                    </div>
                  </button>
                ) : (
                  <>
                    <div className="new-job-file-box-head">
                      <span>{formatMessage(messages.selectedFiles, { count: files.length })}</span>
                    </div>
                    <div className="file-list new-job-file-list">
                      {files.map((file) => (
                        <div key={file.id} className="new-job-file-row">
                          <div>
                            <div className="new-job-file-name">{file.name}</div>
                            <div className="job-meta-line">
                              {file.kind === "audio" ? commonMessages.audio : commonMessages.video} · {file.sizeLabel}
                            </div>
                          </div>
                          <button className="text-button danger-text" type="button" onClick={() => removeFile(file.id)}>
                            {commonMessages.remove}
                          </button>
                        </div>
                      ))}
                    </div>
                  </>
                )}
              </div>
            </section>
          </article>

          <article className="new-job-options-panel">
            <div className="new-job-section-head">
              <div>
                <h3>{messages.advancedSettings}</h3>
                <p>{messages.hotwordsHint}</p>
              </div>
            </div>

            <div className="new-job-options-grid">
              <div className="new-job-option">
                <div>
                  <strong>{messages.language}</strong>
                  <p>{messages.languageHint}</p>
                </div>
                <select id="job-lang" value={lang} onChange={(event) => setLang(event.target.value)}>
                  <option value="zh-CN">{messages.langZh}</option>
                  <option value="en-US">{messages.langEn}</option>
                  <option value="ja-JP">{messages.langJa}</option>
                </select>
              </div>

              <div className="new-job-option">
                <div>
                  <strong>{messages.speaker}</strong>
                  <p>{messages.speakerHint}</p>
                </div>
                <label>
                  <input checked={enableSpeaker} onChange={(event) => setEnableSpeaker(event.target.checked)} type="checkbox" />
                  <span>{enableSpeaker ? commonMessages.enabled : commonMessages.disabled}</span>
                </label>
              </div>

              <div className="field new-job-hotwords-field">
                <label htmlFor="job-hotwords">{messages.hotwords}</label>
                <textarea id="job-hotwords" value={hotwordsText} onChange={(event) => setHotwordsText(event.target.value)} placeholder={messages.hotwordsPlaceholder} />
              </div>
            </div>
          </article>
        </main>

        <aside className="new-job-rail">
          <article className="new-job-submit-card">
            <div className="new-job-status-grid">
              <div>
                <span>{messages.allJobs}</span>
                <strong>{store.jobs.length}</strong>
              </div>
              <div>
                <span>{messages.processing}</span>
                <strong>{activeJobs}</strong>
              </div>
              <div>
                <span>{messages.failed}</span>
                <strong>{failedJobs}</strong>
              </div>
            </div>

            <div className="new-job-check-list">
              <div>
                <strong>{serviceModeLabel}</strong>
                <span>
                  {isLocalMode
                    ? messages.localModeHint
                    : store.settings.backendUrl.trim()
                      ? store.settings.backendUrl
                      : messages.pendingEnvHint}
                </span>
              </div>
              <div>
                <strong>{messages.fileRule}</strong>
                <span>{isLocalMode ? messages.localFileRule : messages.remoteFileRule}</span>
              </div>
            </div>

            {submitError && <div className="error-block new-job-error">{submitError}</div>}

            <button
              className="primary-button new-job-create-button"
              type="button"
              disabled={isSubmitting || !title.trim() || !files.length}
              onClick={submit}
            >
              {isSubmitting ? messages.creating : messages.createJob}
            </button>

            <div className="new-job-rail-actions">
              <button className="text-button" type="button" onClick={() => router.push("/jobs")}>
                {messages.viewJobs}
              </button>
              <button className="text-button" type="button" onClick={() => router.push("/settings")}>
                {messages.settings}
              </button>
            </div>
          </article>

          <article className="new-job-recent-card">
            <div className="new-job-section-head">
              <h3>{messages.recentJobs}</h3>
              <button className="text-button" type="button" onClick={() => router.push("/jobs")}>
                {messages.viewAll}
              </button>
            </div>

            {recentJobs.length ? (
              <div className="job-list compact-list">
                {recentJobs.map((job) => (
                  <div key={job.id} className="new-job-recent-row">
                    <div>
                      <h4>{job.title}</h4>
                      <p>
                        {formatMessage(messages.fileCount, { count: job.sourceFiles.length })} ·{" "}
                        {formatMessage(jobsMessages.minutes, { count: job.durationMinutes })}
                      </p>
                    </div>
                    <button className="text-button recent-job-action" type="button" onClick={() => router.push(`/jobs/${job.id}`)}>
                      {commonMessages.open}
                    </button>
                  </div>
                ))}
              </div>
            ) : (
              <div className="empty-state compact-empty">{messages.noTasks}</div>
            )}
          </article>
        </aside>
      </div>
    </section>
  );
}

// src/views/NewJobView.vue
<script setup lang="ts">
import { open } from "@tauri-apps/plugin-dialog";
import { computed, ref, watch } from "vue";
import { useRouter } from "vue-router";
import { useMeetingStore } from "@/composables/useMeetingStore";
import { formatMessage, getMessages } from "@/services/i18n";
import type { MeetingSourceFile } from "@/types/meeting";

const router = useRouter();
const store = useMeetingStore();

const title = ref("");
const hotwordsText = ref(store.settings.value.defaultHotwords);
const lang = ref("zh-CN");
const enableSpeaker = ref(true);
const files = ref<MeetingSourceFile[]>([]);
const fileInput = ref<HTMLInputElement | null>(null);
const isSubmitting = ref(false);
const submitError = ref("");
const isLocalMode = computed(() => store.localMode.value);
const messages = computed(() => getMessages(store.settings.value.locale).newJob);
const commonMessages = computed(() => getMessages(store.settings.value.locale).common);
const jobsMessages = computed(() => getMessages(store.settings.value.locale).jobs);
const summaryTemplate = computed(
  () => store.settings.value.summaryTemplate.trim() || messages.value.defaultSummaryTemplateName,
);
const serviceModeLabel = computed(() => {
  if (store.localMode.value) {
    return messages.value.localPython;
  }

  if (store.settings.value.backendUrl.trim()) {
    return messages.value.remoteService;
  }

  return messages.value.envMissing;
});

const recentJobs = computed(() => store.jobs.value.slice(0, 4));
const activeJobs = computed(() =>
  store.jobs.value.filter((job) =>
    ["queued", "transcribing", "speaker_processing", "summarizing"].includes(
      job.overallStatus,
    ),
  ).length,
);
const failedJobs = computed(
  () => store.jobs.value.filter((job) => job.overallStatus === "failed").length,
);

watch(
  () => store.settings.value,
  (settings, previous) => {
    const previousHotwords = previous?.defaultHotwords ?? "";

    if (!hotwordsText.value.trim() || hotwordsText.value === previousHotwords) {
      hotwordsText.value = settings.defaultHotwords;
    }
  },
  { deep: true },
);

function inferKind(fileName: string): "audio" | "video" {
  return /\.(mp4|mov|mkv)$/i.test(fileName) ? "video" : "audio";
}

function humanSize(size?: number) {
  if (!size) {
    return commonMessages.value.unknownSize;
  }

  const mb = size / 1024 / 1024;
  return `${mb.toFixed(1)} MB`;
}

function fileNameToTitle(fileName: string) {
  return fileName.replace(/\.[^.]+$/, "").trim();
}

function fileToSource(file: File): MeetingSourceFile {
  return {
    id: crypto.randomUUID(),
    name: file.name,
    sizeLabel: humanSize(file.size),
    kind: inferKind(file.name),
  };
}

function addFiles(next: MeetingSourceFile[]) {
  const lastFile = next.at(-1);

  if (isLocalMode.value) {
    files.value = lastFile ? [lastFile] : files.value;
    if (!title.value.trim() && lastFile) {
      title.value = fileNameToTitle(lastFile.name);
    }
    return;
  }

  files.value = [...files.value, ...next];

  if (!title.value.trim() && lastFile) {
    title.value = fileNameToTitle(lastFile.name);
  }
}

async function pickFiles() {
  try {
    const selected = await open({
      multiple: !isLocalMode.value,
      directory: false,
      filters: [
        {
          name: "Meeting Media",
          extensions: ["m4a", "mp3", "wav", "aac", "flac", "mp4", "mov", "mkv"],
        },
      ],
    });

    if (!selected) {
      return;
    }

    const normalized = Array.isArray(selected) ? selected : [selected];

    addFiles(
      normalized.map((path) => {
        const name = path.split("/").pop() ?? path;

        return {
          id: crypto.randomUUID(),
          name,
          path,
          sizeLabel: commonMessages.value.localPath,
          kind: inferKind(name),
        } satisfies MeetingSourceFile;
      }),
    );
  } catch {
    fileInput.value?.click();
  }
}

function onNativeFileChange(event: Event) {
  const target = event.target as HTMLInputElement;
  const selected = Array.from(target.files ?? []).map(fileToSource);
  addFiles(selected);
  target.value = "";
}

function removeFile(id: string) {
  files.value = files.value.filter((file) => file.id !== id);
}

function clearFiles() {
  files.value = [];
}

async function submit() {
  submitError.value = "";

  if (!files.value.length || !title.value.trim()) {
    return;
  }

  if (isLocalMode.value && files.value.some((file) => !file.path)) {
    submitError.value = messages.value.localPathRequired;
    return;
  }

  isSubmitting.value = true;

  try {
    const job = await store.createJob({
      title: title.value.trim(),
      files: files.value,
      hotwords: hotwordsText.value
        .split(",")
        .map((item) => item.trim())
        .filter(Boolean),
      lang: lang.value,
      enableSpeaker: enableSpeaker.value,
      summaryTemplate: summaryTemplate.value,
    });

    await router.push(`/jobs/${job.id}`);
  } catch (error) {
    submitError.value =
      error instanceof Error ? error.message : messages.value.createFailed;
  } finally {
    isSubmitting.value = false;
  }
}
</script>

<template>
  <section class="view-stack">
    <div class="workspace-grid workspace-grid-home">
      <div class="workspace-primary">
        <article class="surface workbench-hero new-job-hero">
          <div class="job-title-line workbench-hero-head">
            <div>
              <h3>{{ messages.heroTitle }}</h3>
              <p class="section-copy">
                {{ messages.heroCopy }}
              </p>
            </div>
            <button class="text-button" type="button" @click="router.push('/jobs')">
              {{ messages.viewJobs }}
            </button>
          </div>

          <div class="summary-inline">
            <span>{{ messages.allJobs }} {{ store.jobs.value.length }}</span>
            <span>{{ messages.processing }} {{ activeJobs }}</span>
            <span>{{ messages.failed }} {{ failedJobs }}</span>
            <span>{{ serviceModeLabel }}</span>
          </div>
        </article>

        <article class="surface workspace-primary new-job-primary-card">
          <div class="section-heading">
            <div>
              <h3>{{ messages.basicInfo }}</h3>
            </div>
          </div>

          <div class="field task-title-row">
            <label for="job-title">{{ messages.jobTitle }}</label>
            <input
              id="job-title"
              v-model="title"
              :placeholder="messages.titlePlaceholder"
            />
          </div>

          <div class="surface surface-subtle upload-pane new-job-upload-card">
            <div class="section-heading summary-centered-heading">
              <h3>{{ messages.inputFiles }}</h3>
            </div>

            <input
              ref="fileInput"
              type="file"
              accept=".m4a,.mp3,.wav,.aac,.flac,.mp4,.mov,.mkv"
              :multiple="!isLocalMode"
              hidden
              @change="onNativeFileChange"
            />

            <div class="drop-zone new-job-file-box" :class="{ 'has-files': files.length }">
              <button
                v-if="!files.length"
                class="drop-zone-button"
                type="button"
                @click="pickFiles"
              >
                <div class="drop-zone-copy">
                  <strong>{{ messages.addFiles }}</strong>
                  <p class="muted">
                    {{ isLocalMode ? messages.desktopFilePicker : messages.mediaSupported }}
                  </p>
                </div>
              </button>

              <template v-else>
                <div class="new-job-file-box-head">
                  <span class="job-meta-line">
                    {{ formatMessage(messages.selectedFiles, { count: files.length }) }}
                  </span>
                  <div class="new-job-file-box-actions">
                    <button class="text-button" type="button" @click="pickFiles">
                      {{ isLocalMode ? messages.reselect : messages.continueAdding }}
                    </button>
                    <button class="text-button danger-text" type="button" @click="clearFiles">
                      {{ messages.clearList }}
                    </button>
                  </div>
                </div>

                <div class="file-list new-job-file-list">
                  <div v-for="file in files" :key="file.id" class="new-job-file-row">
                    <div class="new-job-file-name">
                      {{ file.name }}
                    </div>
                    <button class="text-button danger-text" type="button" @click="removeFile(file.id)">
                      {{ commonMessages.remove }}
                    </button>
                  </div>
                </div>
              </template>
            </div>
          </div>

          <div v-if="submitError" class="note-block error-block">
            {{ submitError }}
          </div>

          <div class="button-row align-end task-actions">
            <button
              class="primary-button"
              type="button"
              :disabled="isSubmitting || !title.trim() || !files.length"
              @click="submit"
            >
              {{ isSubmitting ? messages.creating : messages.createJob }}
            </button>
          </div>
        </article>

        <article class="surface workspace-primary new-job-settings-card">
          <div class="section-heading">
            <div>
              <h3>{{ messages.advancedSettings }}</h3>
            </div>
          </div>

          <div class="summary-list new-job-settings-list">
            <div class="note-block new-job-setting-item">
              <div class="new-job-setting-head">
                <div>
                  <strong>{{ messages.language }}</strong>
                </div>
                <div class="new-job-setting-control">
                  <select id="job-lang" v-model="lang">
                    <option value="zh-CN">{{ messages.langZh }}</option>
                    <option value="en-US">{{ messages.langEn }}</option>
                    <option value="ja-JP">{{ messages.langJa }}</option>
                  </select>
                </div>
              </div>
              <p class="job-meta-line new-job-setting-copy">
                {{ messages.languageHint }}
              </p>
            </div>

            <div class="note-block new-job-setting-item">
              <div class="new-job-setting-head">
                <div>
                  <strong>{{ messages.speaker }}</strong>
                </div>
                <div class="new-job-setting-control">
                  <label class="toggle-field">
                    <input v-model="enableSpeaker" type="checkbox" />
                    <span>{{ enableSpeaker ? commonMessages.enabled : commonMessages.disabled }}</span>
                  </label>
                </div>
              </div>
              <p class="job-meta-line new-job-setting-copy">
                {{ messages.speakerHint }}
              </p>
            </div>

            <div class="note-block new-job-setting-item">
              <div class="new-job-setting-head">
                <div>
                  <strong>{{ messages.hotwords }}</strong>
                </div>
              </div>
              <textarea
                id="job-hotwords"
                v-model="hotwordsText"
                :placeholder="messages.hotwordsPlaceholder"
              />
              <p class="job-meta-line new-job-setting-copy">
                {{ messages.hotwordsHint }}
              </p>
            </div>

          </div>
        </article>
      </div>

      <div class="side-stack new-job-side-stack">
        <article class="surface side-panel new-job-side-panel">
          <div class="section-heading">
            <h3>{{ messages.currentStatus }}</h3>
          </div>

          <div class="metric-strip metric-strip-tight">
            <div class="metric-pill">
              <span class="job-meta-line">{{ messages.allJobs }}</span>
              <strong>{{ store.jobs.value.length }}</strong>
            </div>

            <div class="metric-pill">
              <span class="job-meta-line">{{ messages.processing }}</span>
              <strong>{{ activeJobs }}</strong>
            </div>

            <div class="metric-pill">
              <span class="job-meta-line">{{ messages.failed }}</span>
              <strong>{{ failedJobs }}</strong>
            </div>
          </div>

          <div class="summary-list">
            <div class="file-pill">
              <div>
                <strong>{{ serviceModeLabel }}</strong>
                <div class="job-meta-line">
                  {{
                    isLocalMode
                      ? messages.localModeHint
                      : store.settings.value.backendUrl.trim()
                        ? store.settings.value.backendUrl
                        : messages.pendingEnvHint
                  }}
                </div>
              </div>
            </div>

            <div class="file-pill">
              <div>
                <strong>{{ messages.fileRule }}</strong>
                <div class="job-meta-line">
                  {{ isLocalMode ? messages.localFileRule : messages.remoteFileRule }}
                </div>
              </div>
            </div>
          </div>

          <div class="button-row">
            <button class="secondary-button" type="button" @click="router.push('/settings')">
              {{ messages.settings }}
            </button>
            <button class="text-button" type="button" @click="router.push('/jobs')">
              {{ messages.jobs }}
            </button>
          </div>
        </article>

        <article class="surface side-panel">
          <div class="section-heading summary-centered-heading">
            <h3>{{ messages.recentJobs }}</h3>
            <button class="text-button" type="button" @click="router.push('/jobs')">
              {{ messages.viewAll }}
            </button>
          </div>

          <div v-if="recentJobs.length" class="job-list compact-list">
            <div
              v-for="job in recentJobs"
              :key="job.id"
              class="job-item compact-job"
            >
              <div class="recent-job-row">
                <div class="recent-job-copy">
                  <h4>{{ job.title }}</h4>
                  <div class="job-meta-line">
                    {{ formatMessage(messages.fileCount, { count: job.sourceFiles.length }) }} · {{ formatMessage(jobsMessages.minutes, { count: job.durationMinutes }) }}
                  </div>
                </div>
                <button class="text-button recent-job-action" type="button" @click="router.push(`/jobs/${job.id}`)">
                  {{ commonMessages.open }}
                </button>
              </div>
            </div>
          </div>

          <div v-else class="empty-state compact-empty">
            {{ messages.noTasks }}
          </div>
        </article>
      </div>
    </div>
  </section>
</template>
