// apps/desktop/src/features/models/views/ModelEditorView.vue
<script setup lang="ts">
import { confirm, message } from "@tauri-apps/plugin-dialog";
import { computed, onMounted, ref, watch } from "vue";
import { useRoute } from "vue-router";
import { getCurrentWindow } from "@tauri-apps/api/window";
import { useAiStore } from "@/features/ai/stores/useAiStore";
import { useMeetingStore } from "@/features/meeting/stores/useMeetingStore";
import { formatMessage, getMessages } from "@/shared/i18n";
import type { AiModelConfig } from "@/shared/types/meeting";

const route = useRoute();
const aiStore = useAiStore();
const meetingStore = useMeetingStore();

const selectedId = ref<string | null>(null);
const draft = ref<AiModelConfig>(createFreshDraft());
const errorMessage = ref("");
const messages = computed(() => getMessages(meetingStore.settings.value.locale).models);
const commonMessages = computed(() => getMessages(meetingStore.settings.value.locale).common);

const selectedModel = computed(() =>
  selectedId.value ? aiStore.getModelById(selectedId.value) ?? null : null,
);

watch(selectedModel, (nextModel) => {
  if (!nextModel) {
    return;
  }

  draft.value = { ...nextModel };
});

onMounted(async () => {
  await aiStore.ensureLoaded();
  const modelId = typeof route.query.id === "string" ? route.query.id : null;

  if (modelId) {
    const model = aiStore.getModelById(modelId);
    if (model) {
      selectedId.value = model.id;
      draft.value = { ...model };
      await syncWindowTitle(true);
      return;
    }
  }

  selectedId.value = null;
  draft.value = createFreshDraft();
  await syncWindowTitle(false);
});

function createFreshDraft() {
  return aiStore.createModel();
}

function validateDraft() {
  if (!draft.value.name.trim()) {
    return messages.value.validationName;
  }

  if (!draft.value.baseUrl.trim()) {
    return messages.value.validationBaseUrl;
  }

  if (!draft.value.apiKey.trim()) {
    return messages.value.validationApiKey;
  }

  if (!draft.value.model.trim()) {
    return messages.value.validationModel;
  }

  return "";
}

async function syncWindowTitle(isEdit: boolean) {
  try {
    await getCurrentWindow().setTitle(isEdit ? messages.value.editorEditTitle : messages.value.editorNewTitle);
  } catch {
    // ignore
  }
}

async function save() {
  const validation = validateDraft();
  const isEditing = !!selectedId.value;

  if (validation) {
    errorMessage.value = validation;
    return;
  }

  await aiStore.saveModel({
    ...draft.value,
    name: draft.value.name.trim(),
    baseUrl: draft.value.baseUrl.trim(),
    apiKey: draft.value.apiKey.trim(),
    model: draft.value.model.trim(),
  });

  selectedId.value = draft.value.id;
  draft.value = { ...(aiStore.getModelById(draft.value.id) ?? draft.value) };
  errorMessage.value = "";
  await syncWindowTitle(true);
  await message(
    formatMessage(
      isEditing ? messages.value.saveSuccessUpdated : messages.value.saveSuccessCreated,
      { name: draft.value.name },
    ),
    { title: messages.value.title, kind: "info" },
  );
}

async function removeModel() {
  if (!selectedModel.value) {
    return;
  }

  const confirmed = await confirm(formatMessage(messages.value.deleteConfirm, { name: selectedModel.value.name }), {
    title: messages.value.deleteTitle,
    kind: "warning",
    okLabel: commonMessages.value.delete,
    cancelLabel: commonMessages.value.cancel,
  });
  if (!confirmed) {
    return;
  }

  await aiStore.deleteModel(selectedModel.value.id);
  selectedId.value = null;
  draft.value = createFreshDraft();
  await syncWindowTitle(false);
}

function resetDraft() {
  selectedId.value = null;
  draft.value = createFreshDraft();
  errorMessage.value = "";
  void syncWindowTitle(false);
}
</script>

<template>
  <section class="editor-window-shell">
    <article class="surface editor-window-card">
      <div class="section-heading">
        <h3>{{ selectedId ? messages.editorEditTitle : messages.editorNewTitle }}</h3>
      </div>

      <div class="field-grid">
        <div class="field">
          <label for="model-name">{{ messages.name }}</label>
          <input id="model-name" v-model="draft.name" :placeholder="messages.namePlaceholder" />
        </div>

        <div class="field">
          <label for="model-base-url">{{ messages.baseUrl }}</label>
          <input
            id="model-base-url"
            v-model="draft.baseUrl"
            :placeholder="messages.baseUrlPlaceholder"
          />
        </div>

        <div class="field">
          <label for="model-api-key">{{ messages.apiKey }}</label>
          <input
            id="model-api-key"
            v-model="draft.apiKey"
            type="password"
            :placeholder="messages.apiKeyPlaceholder"
            autocomplete="off"
          />
        </div>

        <div class="field">
          <label for="model-id">{{ messages.model }}</label>
          <input id="model-id" v-model="draft.model" :placeholder="messages.modelPlaceholder" />
          <p class="field-copy">{{ messages.modelHelp }}</p>
        </div>

        <div class="field-grid two-col">
          <label class="toggle-field">
            <input v-model="draft.enabled" type="checkbox" />
            <span>{{ messages.enabledSwitch }}</span>
          </label>

          <label class="toggle-field">
            <input v-model="draft.isDefault" type="checkbox" />
            <span>{{ messages.defaultSwitch }}</span>
          </label>
        </div>
      </div>

      <div v-if="errorMessage" class="note-block error-block">
        {{ errorMessage }}
      </div>

      <div class="button-row">
        <button class="primary-button" type="button" @click="save">
          {{ messages.save }}
        </button>
        <button class="secondary-button" type="button" @click="resetDraft">
          {{ messages.reset }}
        </button>
        <button
          v-if="selectedId"
          class="text-button danger-text"
          type="button"
          @click="removeModel"
        >
          {{ commonMessages.delete }}
        </button>
      </div>
    </article>
  </section>
</template>

// apps/desktop/src/features/models/views/ModelEditorView.tsx
import { confirm, message } from "@tauri-apps/plugin-dialog";
import { getCurrentWindow } from "@tauri-apps/api/window";
import { useEffect, useState } from "react";
import { useAiStore } from "@/features/ai/stores/useAiStore";
import { useMeetingStore } from "@/features/meeting/stores/useMeetingStore";
import { formatMessage, getMessages } from "@/shared/i18n";
import type { AiModelConfig } from "@/shared/types/meeting";

export default function ModelEditorView() {
  const aiStore = useAiStore();
  const meetingStore = useMeetingStore();
  const [selectedId, setSelectedId] = useState<string | null>(null);
  const [draft, setDraft] = useState<AiModelConfig>(() => aiStore.createModel());
  const [errorMessage, setErrorMessage] = useState("");
  const messages = getMessages(meetingStore.settings.locale).models;
  const commonMessages = getMessages(meetingStore.settings.locale).common;
  const selectedModel = selectedId ? aiStore.getModelById(selectedId) ?? null : null;

  useEffect(() => {
    void initialize();
  }, []);

  async function initialize() {
    await aiStore.ensureLoaded();
    const modelId = new URLSearchParams(window.location.search).get("id");

    if (modelId) {
      const model = aiStore.getModelById(modelId);
      if (model) {
        setSelectedId(model.id);
        setDraft({ ...model });
        await syncWindowTitle(true);
        return;
      }
    }

    setSelectedId(null);
    setDraft(aiStore.createModel());
    await syncWindowTitle(false);
  }

  function patchDraft(patch: Partial<AiModelConfig>) {
    setDraft((current) => ({ ...current, ...patch }));
  }

  function validateDraft() {
    if (!draft.name.trim()) {
      return messages.validationName;
    }
    if (!draft.baseUrl.trim()) {
      return messages.validationBaseUrl;
    }
    if (!selectedId && !draft.apiKey.trim()) {
      return messages.validationApiKey;
    }
    if (!draft.model.trim()) {
      return messages.validationModel;
    }
    return "";
  }

  async function syncWindowTitle(isEdit: boolean) {
    try {
      await getCurrentWindow().setTitle(isEdit ? messages.editorEditTitle : messages.editorNewTitle);
    } catch {
      // ignore
    }
  }

  async function save() {
    const validation = validateDraft();
    const isEditing = !!selectedId;

    if (validation) {
      setErrorMessage(validation);
      return;
    }

    await aiStore.saveModel({
      ...draft,
      name: draft.name.trim(),
      baseUrl: draft.baseUrl.trim(),
      apiKey: draft.apiKey.trim(),
      model: draft.model.trim(),
    });

    setSelectedId(draft.id);
    setDraft({ ...(aiStore.getModelById(draft.id) ?? draft) });
    setErrorMessage("");
    await syncWindowTitle(true);
    await message(
      formatMessage(isEditing ? messages.saveSuccessUpdated : messages.saveSuccessCreated, { name: draft.name }),
      { title: messages.title, kind: "info" },
    );
  }

  async function removeModel() {
    if (!selectedModel) {
      return;
    }

    const confirmed = await confirm(formatMessage(messages.deleteConfirm, { name: selectedModel.name }), {
      title: messages.deleteTitle,
      kind: "warning",
      okLabel: commonMessages.delete,
      cancelLabel: commonMessages.cancel,
    });
    if (!confirmed) {
      return;
    }

    await aiStore.deleteModel(selectedModel.id);
    resetDraft();
  }

  function resetDraft() {
    setSelectedId(null);
    setDraft(aiStore.createModel());
    setErrorMessage("");
    void syncWindowTitle(false);
  }

  return (
    <section className="editor-window-shell native-editor-window">
      <article className="surface editor-window-card native-editor-card">
        <div className="section-heading">
          <h3>{selectedId ? messages.editorEditTitle : messages.editorNewTitle}</h3>
        </div>

        <div className="native-editor-layout">
          <aside className="native-editor-aside">
            <strong>{messages.title}</strong>
            <p>{messages.copy}</p>
            <span>{selectedId ? messages.editorEditTitle : messages.editorNewTitle}</span>
          </aside>

          <div className="field-grid native-editor-form">
            <div className="field">
              <label htmlFor="model-name">{messages.name}</label>
              <input id="model-name" value={draft.name} onChange={(event) => patchDraft({ name: event.target.value })} placeholder={messages.namePlaceholder} />
            </div>
            <div className="field">
              <label htmlFor="model-base-url">{messages.baseUrl}</label>
              <input id="model-base-url" value={draft.baseUrl} onChange={(event) => patchDraft({ baseUrl: event.target.value })} placeholder={messages.baseUrlPlaceholder} />
            </div>
            <div className="field">
              <label htmlFor="model-api-key">{messages.apiKey}</label>
              <input id="model-api-key" value={draft.apiKey} onChange={(event) => patchDraft({ apiKey: event.target.value })} type="password" placeholder={messages.apiKeyPlaceholder} autoComplete="off" />
            </div>
            <div className="field">
              <label htmlFor="model-id">{messages.model}</label>
              <input id="model-id" value={draft.model} onChange={(event) => patchDraft({ model: event.target.value })} placeholder={messages.modelPlaceholder} />
              <p className="field-copy">{messages.modelHelp}</p>
            </div>
            <div className="field-grid two-col">
              <label className="toggle-field">
                <input checked={draft.enabled} onChange={(event) => patchDraft({ enabled: event.target.checked })} type="checkbox" />
                <span>{messages.enabledSwitch}</span>
              </label>
              <label className="toggle-field">
                <input checked={draft.isDefault} onChange={(event) => patchDraft({ isDefault: event.target.checked })} type="checkbox" />
                <span>{messages.defaultSwitch}</span>
              </label>
            </div>
          </div>
        </div>

        {errorMessage && <div className="note-block error-block">{errorMessage}</div>}

        <div className="button-row">
          <button className="primary-button" type="button" onClick={save}>
            {messages.save}
          </button>
          <button className="secondary-button" type="button" onClick={resetDraft}>
            {messages.reset}
          </button>
          {selectedId && (
            <button className="text-button danger-text" type="button" onClick={removeModel}>
              {commonMessages.delete}
            </button>
          )}
        </div>
      </article>
    </section>
  );
}
