// apps/desktop/src/features/settings/views/SettingsView.vue
<script setup lang="ts">
import { computed, onMounted } from "vue";
import progressBarUrl from "@/assets/progress-bar.webp";
import { useMeetingStore } from "@/features/meeting/stores/useMeetingStore";
import { accentColors, useSettingsForm } from "@/features/settings/application/useSettingsForm";
import { useRuntimePanel } from "@/features/settings/application/useRuntimePanel";
import { useDiagnosticsPanel } from "@/shared/services/system/diagnostics";
import { getMessages } from "@/shared/i18n";
import type { LiquidGlassStyle, LocaleCode, ThemeMode } from "@/shared/types/meeting";

const store = useMeetingStore();
const messages = computed(() => getMessages(store.settings.value.locale).settings);
const shellMessages = computed(() => getMessages(store.settings.value.locale).shell);
const commonMessages = computed(() => getMessages(store.settings.value.locale).common);
const {
  form,
  saveError,
  glassPreviewThemeClass,
  setThemeMode,
  setGlassStyle,
  setLocale,
  setAccentColor,
  save,
} = useSettingsForm(store);
const {
  runtimeModeLabel,
  runtimeStatus,
  runtimeInstallLogReversed,
  runtimeActionLabel,
  runtimeStatusLabel,
  runtimeStatusDescription,
  runtimeBusy,
  runtimeInstalledAtLabel,
  runtimeInstallProgress,
  refreshRuntimePanel,
} = useRuntimePanel(store, messages, shellMessages, commonMessages);
const {
  diagnosticsError,
  diagnosticsRows,
  supportedPlatformText,
  refreshDiagnostics,
} = useDiagnosticsPanel();

async function installManagedRuntime() {
  saveError.value = "";

  try {
    await store.installManagedRuntime();
    await refreshRuntimePanel();
  } catch (error) {
    saveError.value = error instanceof Error ? error.message : String(error);
  }
}

onMounted(() => {
  void refreshRuntimePanel();
  void refreshDiagnostics();
});
</script>

<template>
  <section class="settings-page">
    <div class="settings-group">
      <h3 class="settings-group-title">{{ messages.appearance }}</h3>
      <article class="surface settings-block">
        <div class="setting-row">
          <div class="settings-meta">
            <span class="settings-label">{{ messages.themeMode }}</span>
          </div>
          <div class="setting-control">
            <div class="preview-grid preview-grid-3">
              <button class="preview-card" :class="{ active: store.settings.value.themeMode === 'auto' }" type="button"
                @click="setThemeMode('auto')">
                <span class="preview-art preview-theme preview-theme-auto"></span>
                <span class="preview-label">{{ messages.auto }}</span>
              </button>
              <button class="preview-card" :class="{ active: store.settings.value.themeMode === 'light' }" type="button"
                @click="setThemeMode('light')">
                <span class="preview-art preview-theme preview-theme-light"></span>
                <span class="preview-label">{{ messages.light }}</span>
              </button>
              <button class="preview-card" :class="{ active: store.settings.value.themeMode === 'dark' }" type="button"
                @click="setThemeMode('dark')">
                <span class="preview-art preview-theme preview-theme-dark"></span>
                <span class="preview-label">{{ messages.dark }}</span>
              </button>
            </div>
          </div>
        </div>

        <div class="setting-row">
          <div class="settings-meta">
            <span class="settings-label">{{ messages.glassStyle }}</span>
            <p class="settings-hint">{{ messages.glassStyleHint }}</p>
          </div>
          <div class="setting-control">
            <div class="preview-grid preview-grid-2">
              <button class="preview-card" :class="{ active: store.settings.value.liquidGlassStyle === 'transparent' }"
                type="button" @click="setGlassStyle('transparent')">
                <span class="preview-art preview-glass preview-glass-transparent"
                  :class="glassPreviewThemeClass"></span>
                <span class="preview-label">{{ messages.transparent }}</span>
              </button>
              <button class="preview-card" :class="{ active: store.settings.value.liquidGlassStyle === 'tinted' }"
                type="button" @click="setGlassStyle('tinted')">
                <span class="preview-art preview-glass preview-glass-tinted" :class="glassPreviewThemeClass"></span>
                <span class="preview-label">{{ messages.tinted }}</span>
              </button>
            </div>
          </div>
        </div>

        <div class="setting-row">
          <div class="settings-meta">
            <span class="settings-label">{{ messages.locale }}</span>
          </div>
          <div class="setting-control setting-control-inline">
            <select :value="store.settings.value.locale"
              @change="setLocale(($event.target as HTMLSelectElement).value as LocaleCode)">
              <option value="zh-CN">{{ messages.localeZh }}</option>
              <option value="en-US">{{ messages.localeEn }}</option>
            </select>
          </div>
        </div>
      </article>
    </div>

    <div class="settings-group settings-group-accent">
      <h3 class="settings-group-title">{{ messages.themeSection }}</h3>
      <article class="surface settings-block">
        <div class="setting-row setting-row-color">
          <div class="settings-meta">
            <span class="settings-label">{{ messages.accentColor }}</span>
          </div>
          <div class="setting-control">
            <div class="color-row">
              <div v-for="color in accentColors" :key="color" class="color-option">
                <button class="color-dot" :class="{ active: store.settings.value.accentColor.toLowerCase() === color }"
                  :style="{ background: color }" type="button" :title="messages.colorLabels[color]"
                  @click="setAccentColor(color)"></button>
                <span v-if="store.settings.value.accentColor.toLowerCase() === color" class="color-option-label">
                  {{ messages.colorLabels[color] }}
                </span>
              </div>
            </div>
          </div>
        </div>
      </article>
    </div>

    <div class="settings-group">
      <h3 class="settings-group-title">{{ messages.runtimeOverview }}</h3>
      <article class="surface settings-block">
        <div class="setting-row">
          <div class="settings-meta">
            <span class="settings-label">{{ messages.runtimeMode }}</span>
            <p class="settings-hint">{{ messages.runtimeModeHint }}</p>
          </div>
          <div class="setting-control">
            <div class="summary-inline">
              <span>{{ runtimeModeLabel }}</span>
              <span>{{ store.localMode.value ? messages.localDatabaseReady : messages.waitingLocalConfig }}</span>
            </div>
          </div>
        </div>
      </article>
    </div>

    <div class="settings-group">
      <h3 class="settings-group-title">工程诊断</h3>
      <article class="surface settings-block runtime-card">
        <div class="runtime-card-head">
          <div class="runtime-card-title-wrap">
            <span class="runtime-card-title">企业级基线</span>
            <p class="runtime-card-hint">用于验收平台矩阵、数据库版本、运行时状态和安全基线。</p>
          </div>
          <button class="text-button runtime-primary-action" type="button" @click="refreshDiagnostics">
            刷新
          </button>
        </div>

        <div class="runtime-meta-grid diagnostics-grid">
          <div v-for="[label, value] in diagnosticsRows" :key="label" class="runtime-meta-item">
            <span>{{ label }}</span>
            <strong>{{ value }}</strong>
          </div>
        </div>

        <div v-if="supportedPlatformText" class="runtime-log">
          <span class="runtime-log-title">发布平台矩阵</span>
          <pre>{{ supportedPlatformText }}</pre>
        </div>

        <p v-if="diagnosticsError" class="settings-error">{{ diagnosticsError }}</p>
      </article>
    </div>

    <div class="settings-group">
      <h3 class="settings-group-title">{{ messages.localRuntime }}</h3>
      <article class="surface settings-block runtime-card">
        <div class="runtime-card-head">
          <div class="runtime-card-title-wrap">
            <span class="runtime-card-title">{{ messages.managedRuntime }}</span>
            <p class="runtime-card-hint">{{ messages.managedRuntimeHint }}</p>
          </div>
          <div class="runtime-card-status">
            <span class="runtime-status-label">{{ messages.runtimeStatus }}</span>
            <span class="runtime-status-badge" :class="`runtime-status-${runtimeStatus.status}`">
              {{ runtimeStatusLabel }}
            </span>
          </div>
        </div>

        <div class="runtime-panel">
          <div class="runtime-hero">
            <p class="runtime-status-text">{{ runtimeStatusDescription }}</p>
            <button class="text-button runtime-primary-action" type="button" :disabled="runtimeBusy"
              @click="installManagedRuntime">
              {{ runtimeActionLabel }}
            </button>
          </div>

          <div v-if="runtimeStatus.status === 'installing' || runtimeInstallProgress.percent > 0"
            class="runtime-progress-card">
            <div class="runtime-progress-head">
              <span>{{ messages.runtimeInstallProgress }}</span>
              <strong>{{ runtimeInstallProgress.percent }}%</strong>
            </div>
            <div class="runtime-progress-track">
              <span class="runtime-progress-bar" :style="{ width: `${runtimeInstallProgress.percent}%` }">
                <img class="runtime-progress-media" :src="progressBarUrl" alt="" aria-hidden="true" />
              </span>
            </div>
            <div class="runtime-progress-copy">
              {{ runtimeInstallProgress.label }}
            </div>
          </div>

          <div class="runtime-meta-grid">
            <div class="runtime-meta-item">
              <span>{{ messages.runtimeVersion }}</span>
              <strong>{{ runtimeStatus.runtimeVersion || "—" }}</strong>
            </div>
            <div class="runtime-meta-item">
              <span>{{ messages.runtimePythonVersion }}</span>
              <strong>{{ runtimeStatus.pythonVersion || "—" }}</strong>
            </div>
            <div class="runtime-meta-item">
              <span>{{ messages.runtimeInstalledAt }}</span>
              <strong>{{ runtimeInstalledAtLabel }}</strong>
            </div>
          </div>

          <div class="runtime-log">
            <span class="runtime-log-title">{{ messages.runtimeInstallLog }}</span>
            <pre>{{ runtimeInstallLogReversed || messages.runtimeInstallLogEmpty }}</pre>
          </div>
        </div>
      </article>
    </div>

    <div class="settings-group">
      <h3 class="settings-group-title">{{ messages.processingDefaults }}</h3>
      <article class="surface settings-block">
        <div class="setting-row">
          <div class="settings-meta">
            <span class="settings-label">{{ messages.defaultHotwords }}</span>
            <p class="settings-hint">{{ messages.defaultHotwordsHint }}</p>
          </div>
          <div class="setting-control">
            <textarea id="default-hotwords" v-model="form.defaultHotwords"
              :placeholder="messages.defaultHotwordsPlaceholder" @blur="save" />
          </div>
        </div>

        <div class="setting-row">
          <div class="settings-meta">
            <span class="settings-label">{{ messages.defaultSummaryTemplate }}</span>
            <p class="settings-hint">{{ messages.defaultSummaryTemplateHint }}</p>
          </div>
          <div class="setting-control">
            <input id="summary-template" v-model="form.summaryTemplate"
              :placeholder="messages.defaultSummaryTemplatePlaceholder" @blur="save" />
          </div>
        </div>

        <div class="setting-row">
          <div class="settings-meta">
            <span class="settings-label">{{ messages.concurrency }}</span>
            <p class="settings-hint">{{ messages.concurrencyHint }}</p>
          </div>
          <div class="setting-control setting-control-inline">
            <input id="concurrency" v-model.number="form.concurrency" type="number" min="1" max="8" @blur="save" />
          </div>
        </div>

        <div class="setting-row">
          <div class="settings-meta">
            <span class="settings-label">{{ messages.localAsrDevice }}</span>
            <p class="settings-hint">{{ messages.localAsrDeviceHint }}</p>
          </div>
          <div class="setting-control setting-control-inline">
            <select v-model="form.localAsrDevice" @change="save">
              <option value="auto">{{ messages.localAsrDeviceAuto }}</option>
              <option value="cpu">{{ messages.localAsrDeviceCpu }}</option>
              <option value="mps">{{ messages.localAsrDeviceMps }}</option>
              <option value="cuda">{{ messages.localAsrDeviceCuda }}</option>
            </select>
          </div>
        </div>

        <div class="setting-row">
          <div class="settings-meta">
            <span class="settings-label">{{ messages.localAsrThreads }}</span>
            <p class="settings-hint">{{ messages.localAsrThreadsHint }}</p>
          </div>
          <div class="setting-control setting-control-inline">
            <input id="local-asr-threads" v-model.number="form.localAsrThreads" type="number" min="0" max="32"
              @blur="save" />
          </div>
        </div>

        <div class="setting-row">
          <div class="settings-meta">
            <span class="settings-label">{{ messages.localAsrBatchSizeSeconds }}</span>
            <p class="settings-hint">{{ messages.localAsrBatchSizeSecondsHint }}</p>
          </div>
          <div class="setting-control setting-control-inline">
            <input id="local-asr-batch-size-seconds" v-model.number="form.localAsrBatchSizeSeconds" type="number"
              min="30" max="1200" step="30" @blur="save" />
          </div>
        </div>
      </article>
    </div>

    <div class="settings-group">
      <h3 class="settings-group-title">{{ messages.remoteCompatibility }}</h3>
      <article class="surface settings-block">
        <div class="setting-row">
          <div class="settings-meta">
            <span class="settings-label">{{ messages.backendUrl }}</span>
            <p class="settings-hint">{{ messages.backendUrlHint }}</p>
          </div>
          <div class="setting-control">
            <input id="backend-url" v-model="form.backendUrl" :placeholder="messages.backendUrlPlaceholder"
              @blur="save" />
          </div>
        </div>

        <div class="setting-row">
          <div class="settings-meta">
            <span class="settings-label">{{ messages.apiToken }}</span>
            <p class="settings-hint">{{ messages.apiTokenHint }}</p>
          </div>
          <div class="setting-control">
            <input id="api-token" v-model="form.apiToken" type="password" :placeholder="messages.apiTokenPlaceholder"
              autocomplete="off" @blur="save" />
          </div>
        </div>
      </article>
    </div>

    <p v-if="saveError" class="settings-error">{{ saveError }}</p>

    <footer class="settings-footer">
      <p>{{ messages.copyright }}</p>
      <p>
        {{ messages.authorGithub }}
        <a href="https://github.com/westng/Liberty" target="_blank" rel="noreferrer">github.com/westng/Liberty</a>
      </p>
    </footer>
  </section>
</template>

<style scoped>
.runtime-panel {
  display: grid;
  gap: 18px;
}

.runtime-card {
  display: grid;
  gap: 22px;
  padding: 18px 18px 16px;
}

.runtime-card::after {
  display: none;
}

.runtime-card-head {
  display: flex;
  align-items: flex-start;
  justify-content: space-between;
  gap: 24px;
  padding-bottom: 16px;
  border-bottom: 1px solid var(--divider-soft);
}

.runtime-card-title-wrap {
  display: grid;
  gap: 6px;
  max-width: 760px;
}

.runtime-card-title {
  font-size: 1.02rem;
  font-weight: 700;
  color: var(--text-main);
  line-height: 1.2;
}

.runtime-card-hint {
  margin: 0;
  color: var(--text-muted);
  line-height: 1.55;
}

.runtime-card-status {
  display: grid;
  justify-items: end;
  gap: 8px;
  flex-shrink: 0;
}

.runtime-status-label {
  color: var(--text-secondary);
  font-size: 13px;
}

.runtime-status-badge {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  min-width: 84px;
  padding: 6px 12px;
  border-radius: var(--radius-pill);
  font-size: 12px;
  font-weight: 600;
  background: color-mix(in srgb, var(--bg-input) 88%, transparent);
  border: 1px solid color-mix(in srgb, var(--divider-soft) 72%, transparent);
}

.runtime-hero {
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: 20px;
}

.runtime-status-ready {
  color: rgb(31, 140, 84);
  background: rgba(41, 171, 107, 0.14);
}

.runtime-status-installing {
  color: rgb(191, 119, 9);
  background: rgba(255, 176, 32, 0.16);
}

.runtime-status-idle,
.runtime-status-upToDate,
.runtime-status-restartRequired {
  color: rgb(31, 140, 84);
  background: rgba(41, 171, 107, 0.14);
}

.runtime-status-checking,
.runtime-status-downloading,
.runtime-status-updateAvailable {
  color: rgb(191, 119, 9);
  background: rgba(255, 176, 32, 0.16);
}

.runtime-status-failed,
.runtime-status-repair_required,
.runtime-status-error,
.runtime-status-unsupported {
  color: rgb(191, 60, 60);
  background: rgba(255, 106, 87, 0.16);
}

.runtime-status-text {
  margin: 0;
  color: var(--text-secondary);
  line-height: 1.6;
  max-width: 760px;
  font-size: 14px;
}

.runtime-meta-grid {
  display: grid;
  grid-template-columns: repeat(3, minmax(0, 1fr));
  gap: 12px;
}

.runtime-progress-card {
  display: grid;
  gap: 10px;
  padding: 14px 16px;
  border-radius: var(--radius-xl);
  background:
    linear-gradient(180deg,
      color-mix(in srgb, var(--bg-card) 96%, transparent) 0%,
      color-mix(in srgb, var(--bg-panel) 92%, transparent) 100%);
  border: 1px solid color-mix(in srgb, var(--divider-soft) 86%, transparent);
}

.runtime-progress-head {
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: 16px;
  color: var(--text-secondary);
  font-size: 13px;
}

.runtime-progress-head strong {
  color: var(--text-main);
  font-size: 13px;
  font-weight: 700;
}

.runtime-progress-track {
  position: relative;
  height: 8px;
  border-radius: var(--radius-pill);
  background: color-mix(in srgb, var(--bg-input) 92%, var(--text-soft) 8%);
  border: 1px solid color-mix(in srgb, var(--divider-soft) 80%, transparent);
}

.runtime-progress-bar {
  display: block;
  position: relative;
  height: 100%;
  border-radius: inherit;
  overflow: visible;
  background:
    linear-gradient(90deg,
      color-mix(in srgb, var(--accent) 78%, white 22%) 0%,
      var(--accent) 28%,
      color-mix(in srgb, var(--accent) 58%, white 42%) 50%,
      var(--accent) 72%,
      color-mix(in srgb, var(--accent) 78%, white 22%) 100%);
  background-size: 220% 100%;
  box-shadow: 0 0 18px color-mix(in srgb, var(--accent) 24%, transparent);
  transition: width 220ms ease;
  animation: runtime-progress-flow 1.8s linear infinite;
}

.runtime-progress-media {
  position: absolute;
  top: 50%;
  right: -14px;
  width: 38px;
  height: 38px;
  object-fit: contain;
  transform: translateY(-50%);
  opacity: 0.98;
  pointer-events: none;
  z-index: 2;
  filter: drop-shadow(0 6px 12px rgba(0, 0, 0, 0.18));
}

.runtime-progress-copy {
  color: var(--text-secondary);
  font-size: 13px;
  line-height: 1.5;
}

@keyframes runtime-progress-flow {
  from {
    background-position: 200% 0;
  }

  to {
    background-position: 0 0;
  }
}

@media (prefers-reduced-motion: reduce) {
  .runtime-progress-bar {
    animation: none;
  }
}

.runtime-meta-item {
  display: grid;
  gap: 8px;
  padding: 15px 16px;
  border-radius: var(--radius-xl);
  background:
    linear-gradient(180deg,
      color-mix(in srgb, var(--bg-card) 96%, transparent) 0%,
      color-mix(in srgb, var(--bg-panel) 92%, transparent) 100%);
  border: 1px solid color-mix(in srgb, var(--divider-soft) 88%, transparent);
}

.runtime-meta-item span {
  color: var(--text-secondary);
  font-size: 12px;
  font-weight: 600;
}

.runtime-meta-item strong {
  font-size: 15px;
  font-weight: 600;
  line-height: 1.35;
}

.update-feed-label {
  word-break: break-all;
}

.runtime-primary-action {
  flex-shrink: 0;
  white-space: nowrap;
}

.runtime-primary-action.text-button[disabled] {
  opacity: 0.5;
  cursor: not-allowed;
}

.runtime-log {
  display: grid;
  gap: 10px;
}

.runtime-log-title {
  font-size: 0.95rem;
  font-weight: 700;
  color: var(--text-main);
}

.runtime-log pre {
  margin: 0;
  max-height: 220px;
  overflow: auto;
  padding: 14px 16px;
  border-radius: var(--radius-xl);
  background:
    linear-gradient(180deg,
      color-mix(in srgb, var(--bg-input) 94%, transparent) 0%,
      color-mix(in srgb, var(--bg-card) 88%, transparent) 100%);
  border: 1px solid color-mix(in srgb, var(--divider-soft) 86%, transparent);
  color: var(--text-secondary);
  font-size: 12px;
  line-height: 1.55;
  white-space: pre-wrap;
  word-break: break-word;
}

@media (max-width: 980px) {
  .runtime-card-head {
    flex-direction: column;
    align-items: stretch;
  }

  .runtime-card-status {
    justify-content: space-between;
    justify-items: stretch;
  }

  .runtime-hero {
    flex-direction: column;
    align-items: stretch;
  }

  .runtime-meta-grid {
    grid-template-columns: 1fr;
  }
}
</style>

// apps/desktop/src/features/settings/views/SettingsView.tsx
import { useEffect } from "react";
import progressBarUrl from "@/assets/progress-bar.webp";
import { useMeetingStore } from "@/features/meeting/stores/useMeetingStore";
import { accentColors, useSettingsForm } from "@/features/settings/application/useSettingsForm";
import { useRuntimePanel } from "@/features/settings/application/useRuntimePanel";
import { useDiagnosticsPanel } from "@/shared/services/system/diagnostics";
import { getMessages } from "@/shared/i18n";
import type { LiquidGlassStyle, LocaleCode, LocalAsrDevice, ThemeMode } from "@/shared/types/meeting";
import "./SettingsView.css";

export default function SettingsView() {
  const store = useMeetingStore();
  const messages = getMessages(store.settings.locale).settings;
  const shellMessages = getMessages(store.settings.locale).shell;
  const commonMessages = getMessages(store.settings.locale).common;
  const {
    form,
    patchForm,
    saveError,
    setSaveError,
    effectiveTheme,
    glassPreviewThemeClass,
    setThemeMode,
    setGlassStyle,
    setLocale,
    setAccentColor,
    save,
  } = useSettingsForm(store);
  const {
    runtimeModeLabel,
    runtimeStatus,
    runtimeInstallLogReversed,
    runtimeActionLabel,
    runtimeStatusLabel,
    runtimeStatusDescription,
    runtimeBusy,
    runtimeInstalledAtLabel,
    runtimeInstallProgress,
    refreshRuntimePanel,
  } = useRuntimePanel(store, messages, shellMessages, commonMessages);
  const {
    diagnostics,
    diagnosticsError,
    diagnosticsRows,
    supportedPlatformText,
    refreshDiagnostics,
  } = useDiagnosticsPanel();

  useEffect(() => {
    void refreshRuntimePanel();
    void refreshDiagnostics();
  }, []);

  async function installManagedRuntime() {
    setSaveError("");

    try {
      await store.installManagedRuntime();
      await refreshRuntimePanel();
    } catch (error) {
      setSaveError(error instanceof Error ? error.message : String(error));
    }
  }

  return (
    <section className="settings-page">
      <div className="settings-group">
        <h3 className="settings-group-title">{messages.appearance}</h3>
        <article className="surface settings-block">
          <div className="setting-row">
            <div className="settings-meta">
              <span className="settings-label">{messages.themeMode}</span>
              <p className="settings-hint">
                {messages.effectiveTheme}: {effectiveTheme === "dark" ? messages.dark : messages.light}
              </p>
            </div>
            <div className="setting-control">
              <div className="preview-grid preview-grid-3">
                {(["auto", "light", "dark"] as ThemeMode[]).map((mode) => (
                  <button
                    key={mode}
                    className={`preview-card ${store.settings.themeMode === mode ? "active" : ""}`}
                    type="button"
                    onClick={() => setThemeMode(mode)}
                  >
                    <span className={`preview-art preview-theme preview-theme-${mode}`} />
                    <span className="preview-label">{mode === "auto" ? messages.auto : mode === "light" ? messages.light : messages.dark}</span>
                  </button>
                ))}
              </div>
            </div>
          </div>

          <div className="setting-row">
            <div className="settings-meta">
              <span className="settings-label">{messages.glassStyle}</span>
              <p className="settings-hint">{messages.glassStyleHint}</p>
            </div>
            <div className="setting-control">
              <div className="preview-grid preview-grid-2">
                {(["transparent", "tinted"] as LiquidGlassStyle[]).map((style) => (
                  <button
                    key={style}
                    className={`preview-card ${store.settings.liquidGlassStyle === style ? "active" : ""}`}
                    type="button"
                    onClick={() => setGlassStyle(style)}
                  >
                    <span className={`preview-art preview-glass preview-glass-${style} ${glassPreviewThemeClass}`} />
                    <span className="preview-label">{style === "transparent" ? messages.transparent : messages.tinted}</span>
                  </button>
                ))}
              </div>
            </div>
          </div>

          <div className="setting-row">
            <div className="settings-meta">
              <span className="settings-label">{messages.locale}</span>
            </div>
            <div className="setting-control setting-control-inline">
              <select value={store.settings.locale} onChange={(event) => setLocale(event.target.value as LocaleCode)}>
                <option value="zh-CN">{messages.localeZh}</option>
                <option value="en-US">{messages.localeEn}</option>
              </select>
            </div>
          </div>
        </article>
      </div>

      <div className="settings-group settings-group-accent">
        <h3 className="settings-group-title">{messages.themeSection}</h3>
        <article className="surface settings-block">
          <div className="setting-row setting-row-color">
            <div className="settings-meta">
              <span className="settings-label">{messages.accentColor}</span>
            </div>
            <div className="setting-control">
              <div className="color-row">
                {accentColors.map((color) => (
                  <div key={color} className="color-option">
                    <button
                      className={`color-dot ${store.settings.accentColor.toLowerCase() === color ? "active" : ""}`}
                      style={{ background: color }}
                      type="button"
                      title={messages.colorLabels[color]}
                      onClick={() => setAccentColor(color)}
                    />
                    {store.settings.accentColor.toLowerCase() === color && (
                      <span className="color-option-label">{messages.colorLabels[color]}</span>
                    )}
                  </div>
                ))}
              </div>
            </div>
          </div>
        </article>
      </div>

      <div className="settings-group">
        <h3 className="settings-group-title">{messages.runtimeOverview}</h3>
        <article className="surface settings-block">
          <div className="setting-row">
            <div className="settings-meta">
              <span className="settings-label">{messages.runtimeMode}</span>
              <p className="settings-hint">{messages.runtimeModeHint}</p>
            </div>
            <div className="setting-control">
              <div className="summary-inline">
                <span>{runtimeModeLabel}</span>
                <span>{store.localMode ? messages.localDatabaseReady : messages.waitingLocalConfig}</span>
              </div>
            </div>
          </div>
        </article>
      </div>

      <div className="settings-group">
        <h3 className="settings-group-title">工程诊断</h3>
        <article className="surface settings-block runtime-card diagnostics-card">
          <div className="runtime-card-head">
            <div className="runtime-card-title-wrap">
              <span className="runtime-card-title">企业级基线</span>
              <p className="runtime-card-hint">用于验收平台矩阵、数据库版本、运行时状态和安全基线。</p>
            </div>
            <button className="text-button runtime-primary-action" type="button" onClick={refreshDiagnostics}>
              刷新
            </button>
          </div>

          <div className="runtime-meta-grid diagnostics-grid">
            {diagnosticsRows.map(([label, value]) => (
              <div key={label} className="runtime-meta-item">
                <span>{label}</span>
                <strong>{value}</strong>
              </div>
            ))}
          </div>

          {supportedPlatformText && (
            <div className="runtime-log">
              <span className="runtime-log-title">发布平台矩阵</span>
              <pre>{supportedPlatformText}</pre>
            </div>
          )}

          {diagnostics?.desktopPetDiagnosticLogTail && (
            <div className="runtime-log">
              <span className="runtime-log-title">桌宠拖拽诊断日志</span>
              <pre>{diagnostics.desktopPetDiagnosticLogTail}</pre>
            </div>
          )}

          {diagnosticsError && <p className="settings-error">{diagnosticsError}</p>}
        </article>
      </div>

      <div className="settings-group">
        <h3 className="settings-group-title">{messages.localRuntime}</h3>
        <article className="surface settings-block runtime-card">
          <div className="runtime-card-head">
            <div className="runtime-card-title-wrap">
              <span className="runtime-card-title">{messages.managedRuntime}</span>
              <p className="runtime-card-hint">{messages.managedRuntimeHint}</p>
            </div>
            <div className="runtime-card-status">
              <span className="runtime-status-label">{messages.runtimeStatus}</span>
              <span className={`runtime-status-badge runtime-status-${runtimeStatus.status}`}>
                {runtimeStatusLabel}
              </span>
            </div>
          </div>

          <div className="runtime-panel">
            <div className="runtime-hero">
              <p className="runtime-status-text">{runtimeStatusDescription}</p>
              <button className="text-button runtime-primary-action" type="button" disabled={runtimeBusy} onClick={installManagedRuntime}>
                {runtimeActionLabel}
              </button>
            </div>

            {(runtimeStatus.status === "installing" || runtimeInstallProgress.percent > 0) && (
              <div className="runtime-progress-card">
                <div className="runtime-progress-head">
                  <span>{messages.runtimeInstallProgress}</span>
                  <strong>{runtimeInstallProgress.percent}%</strong>
                </div>
                <div className="runtime-progress-track">
                  <span className="runtime-progress-bar" style={{ width: `${runtimeInstallProgress.percent}%` }}>
                    <img className="runtime-progress-media" src={progressBarUrl} alt="" aria-hidden="true" />
                  </span>
                </div>
                <div className="runtime-progress-copy">{runtimeInstallProgress.label}</div>
              </div>
            )}

            <div className="runtime-meta-grid">
              <div className="runtime-meta-item">
                <span>{messages.runtimeVersion}</span>
                <strong>{runtimeStatus.runtimeVersion || "—"}</strong>
              </div>
              <div className="runtime-meta-item">
                <span>{messages.runtimePythonVersion}</span>
                <strong>{runtimeStatus.pythonVersion || "—"}</strong>
              </div>
              <div className="runtime-meta-item">
                <span>{messages.runtimeInstalledAt}</span>
                <strong>{runtimeInstalledAtLabel}</strong>
              </div>
            </div>

            <div className="runtime-log">
              <span className="runtime-log-title">{messages.runtimeInstallLog}</span>
              <pre>{runtimeInstallLogReversed || messages.runtimeInstallLogEmpty}</pre>
            </div>
          </div>
        </article>
      </div>

      <div className="settings-group">
        <h3 className="settings-group-title">{messages.processingDefaults}</h3>
        <article className="surface settings-block">
          <div className="setting-row">
            <div className="settings-meta">
              <span className="settings-label">{messages.defaultHotwords}</span>
              <p className="settings-hint">{messages.defaultHotwordsHint}</p>
            </div>
            <div className="setting-control">
              <textarea id="default-hotwords" value={form.defaultHotwords} onChange={(event) => patchForm({ defaultHotwords: event.target.value })} placeholder={messages.defaultHotwordsPlaceholder} onBlur={save} />
            </div>
          </div>

          <div className="setting-row">
            <div className="settings-meta">
              <span className="settings-label">{messages.defaultSummaryTemplate}</span>
              <p className="settings-hint">{messages.defaultSummaryTemplateHint}</p>
            </div>
            <div className="setting-control">
              <input id="summary-template" value={form.summaryTemplate} onChange={(event) => patchForm({ summaryTemplate: event.target.value })} placeholder={messages.defaultSummaryTemplatePlaceholder} onBlur={save} />
            </div>
          </div>

          <div className="setting-row">
            <div className="settings-meta">
              <span className="settings-label">{messages.concurrency}</span>
              <p className="settings-hint">{messages.concurrencyHint}</p>
            </div>
            <div className="setting-control setting-control-inline">
              <input id="concurrency" value={form.concurrency} onChange={(event) => patchForm({ concurrency: Number(event.target.value) })} type="number" min="1" max="8" onBlur={save} />
            </div>
          </div>

          <div className="setting-row">
            <div className="settings-meta">
              <span className="settings-label">{messages.localAsrDevice}</span>
              <p className="settings-hint">{messages.localAsrDeviceHint}</p>
            </div>
            <div className="setting-control setting-control-inline">
              <select value={form.localAsrDevice} onChange={(event) => {
                patchForm({ localAsrDevice: event.target.value as LocalAsrDevice });
                void save();
              }}>
                <option value="auto">{messages.localAsrDeviceAuto}</option>
                <option value="cpu">{messages.localAsrDeviceCpu}</option>
                <option value="mps">{messages.localAsrDeviceMps}</option>
                <option value="cuda">{messages.localAsrDeviceCuda}</option>
              </select>
            </div>
          </div>

          <div className="setting-row">
            <div className="settings-meta">
              <span className="settings-label">{messages.localAsrThreads}</span>
              <p className="settings-hint">{messages.localAsrThreadsHint}</p>
            </div>
            <div className="setting-control setting-control-inline">
              <input id="local-asr-threads" value={form.localAsrThreads} onChange={(event) => patchForm({ localAsrThreads: Number(event.target.value) })} type="number" min="0" max="32" onBlur={save} />
            </div>
          </div>

          <div className="setting-row">
            <div className="settings-meta">
              <span className="settings-label">{messages.localAsrBatchSizeSeconds}</span>
              <p className="settings-hint">{messages.localAsrBatchSizeSecondsHint}</p>
            </div>
            <div className="setting-control setting-control-inline">
              <input id="local-asr-batch-size-seconds" value={form.localAsrBatchSizeSeconds} onChange={(event) => patchForm({ localAsrBatchSizeSeconds: Number(event.target.value) })} type="number" min="30" max="1200" step="30" onBlur={save} />
            </div>
          </div>
        </article>
      </div>

      <div className="settings-group">
        <h3 className="settings-group-title">{messages.remoteCompatibility}</h3>
        <article className="surface settings-block">
          <div className="setting-row">
            <div className="settings-meta">
              <span className="settings-label">{messages.backendUrl}</span>
              <p className="settings-hint">{messages.backendUrlHint}</p>
            </div>
            <div className="setting-control">
              <input id="backend-url" value={form.backendUrl} onChange={(event) => patchForm({ backendUrl: event.target.value })} placeholder={messages.backendUrlPlaceholder} onBlur={save} />
            </div>
          </div>

          <div className="setting-row">
            <div className="settings-meta">
              <span className="settings-label">{messages.apiToken}</span>
              <p className="settings-hint">{messages.apiTokenHint}</p>
            </div>
            <div className="setting-control">
              <input id="api-token" value={form.apiToken} onChange={(event) => patchForm({ apiToken: event.target.value })} type="password" placeholder={messages.apiTokenPlaceholder} autoComplete="off" onBlur={save} />
            </div>
          </div>
        </article>
      </div>

      {saveError && <p className="settings-error">{saveError}</p>}

      <footer className="settings-footer">
        <p>{messages.copyright}</p>
        <p>
          {messages.authorGithub}{" "}
          <a href="https://github.com/westng/Liberty" target="_blank" rel="noreferrer">github.com/westng/Liberty</a>
        </p>
      </footer>
    </section>
  );
}
