// apps/desktop/src/shared/components/MeetingNotesPanel.tsx
import { useMeetingStore } from "@/features/meeting/stores/useMeetingStore";
import { getMessages } from "@/shared/i18n";
import type { MeetingSummary } from "@/shared/types/meeting";

type MeetingNotesPanelProps = {
  summary: MeetingSummary;
};

export default function MeetingNotesPanel({ summary }: MeetingNotesPanelProps) {
  const store = useMeetingStore();
  const messages = getMessages(store.settings.locale).notes;

  return (
    <div className="notes-list">
      <article className="note-block">
        <div className="notes-head">
          <h4>{messages.summary}</h4>
        </div>
        <div className="note-content">{summary.overview || messages.emptySummary}</div>
      </article>

      {summary.topics.length > 0 && (
        <article className="note-block">
          <div className="notes-head">
            <h4>{messages.topics}</h4>
          </div>
          <ul className="note-list">
            {summary.topics.map((item) => (
              <li key={item}>{item}</li>
            ))}
          </ul>
        </article>
      )}

      {summary.decisions.length > 0 && (
        <article className="note-block">
          <div className="notes-head">
            <h4>{messages.decisions}</h4>
          </div>
          <ul className="note-list">
            {summary.decisions.map((item) => (
              <li key={item}>{item}</li>
            ))}
          </ul>
        </article>
      )}

      {summary.actionItems.length > 0 && (
        <article className="note-block">
          <div className="notes-head">
            <h4>{messages.actionItems}</h4>
          </div>
          <ul className="note-list">
            {summary.actionItems.map((item) => (
              <li key={item}>{item}</li>
            ))}
          </ul>
        </article>
      )}

      {summary.risks?.length ? (
        <article className="note-block">
          <div className="notes-head">
            <h4>{messages.risks}</h4>
          </div>
          <ul className="note-list">
            {summary.risks.map((item) => (
              <li key={item}>{item}</li>
            ))}
          </ul>
        </article>
      ) : null}

      {summary.followUps?.length ? (
        <article className="note-block">
          <div className="notes-head">
            <h4>{messages.followUps}</h4>
          </div>
          <ul className="note-list">
            {summary.followUps.map((item) => (
              <li key={item}>{item}</li>
            ))}
          </ul>
        </article>
      ) : null}
    </div>
  );
}

// src/components/MeetingNotesPanel.vue
<script setup lang="ts">
import { computed } from "vue";
import { useMeetingStore } from "@/composables/useMeetingStore";
import { getMessages } from "@/services/i18n";
import type { MeetingSummary } from "@/types/meeting";

defineProps<{
  summary: MeetingSummary;
}>();

const store = useMeetingStore();
const messages = computed(() => getMessages(store.settings.value.locale).notes);
</script>

<template>
  <div class="notes-list">
    <article class="note-block">
      <div class="notes-head">
        <h4>{{ messages.summary }}</h4>
      </div>
      <div class="note-content">
        {{ summary.overview || messages.emptySummary }}
      </div>
    </article>

    <article v-if="summary.topics.length" class="note-block">
      <div class="notes-head">
        <h4>{{ messages.topics }}</h4>
      </div>
      <ul class="note-list">
        <li v-for="item in summary.topics" :key="item">{{ item }}</li>
      </ul>
    </article>

    <article v-if="summary.decisions.length" class="note-block">
      <div class="notes-head">
        <h4>{{ messages.decisions }}</h4>
      </div>
      <ul class="note-list">
        <li v-for="item in summary.decisions" :key="item">{{ item }}</li>
      </ul>
    </article>

    <article v-if="summary.actionItems.length" class="note-block">
      <div class="notes-head">
        <h4>{{ messages.actionItems }}</h4>
      </div>
      <ul class="note-list">
        <li v-for="item in summary.actionItems" :key="item">{{ item }}</li>
      </ul>
    </article>

    <article v-if="summary.risks?.length" class="note-block">
      <div class="notes-head">
        <h4>{{ messages.risks }}</h4>
      </div>
      <ul class="note-list">
        <li v-for="item in summary.risks" :key="item">{{ item }}</li>
      </ul>
    </article>

    <article v-if="summary.followUps?.length" class="note-block">
      <div class="notes-head">
        <h4>{{ messages.followUps }}</h4>
      </div>
      <ul class="note-list">
        <li v-for="item in summary.followUps" :key="item">{{ item }}</li>
      </ul>
    </article>
  </div>
</template>
