// apps/desktop/src/shared/components/StatusBadge.tsx
import { useMeetingStore } from "@/features/meeting/stores/useMeetingStore";
import { getMessages } from "@/shared/i18n";
import type { JobStage } from "@/shared/types/meeting";

type StatusBadgeProps = {
  status: JobStage;
  text?: string;
};

export default function StatusBadge({ status, text }: StatusBadgeProps) {
  const store = useMeetingStore();
  const labels = getMessages(store.settings.locale).status;
  const label = text ?? labels[status];

  return <span className={`status-badge status-${status}`}>{label}</span>;
}

// src/components/StatusBadge.vue
<script setup lang="ts">
import { computed } from "vue";
import { useMeetingStore } from "@/composables/useMeetingStore";
import { getMessages } from "@/services/i18n";
import type { JobStage } from "@/types/meeting";

const props = defineProps<{
  status: JobStage;
  text?: string;
}>();

const store = useMeetingStore();
const labels = computed(() => getMessages(store.settings.value.locale).status);

const label = computed(() => props.text ?? labels.value[props.status]);
</script>

<template>
  <span class="status-badge" :class="`status-${status}`">
    {{ label }}
  </span>
</template>
