// apps/desktop/src/features/members/views/MemberEditorView.vue
<script setup lang="ts">
import { confirm } from "@tauri-apps/plugin-dialog";
import { getCurrentWindow } from "@tauri-apps/api/window";
import { computed, onMounted, reactive, ref } from "vue";
import { useRoute } from "vue-router";
import { useMeetingStore } from "@/features/meeting/stores/useMeetingStore";
import { formatMessage, getMessages } from "@/shared/i18n";
import { createLocalMembersService } from "@/shared/services/tauri/members";
import type { MeetingMember } from "@/shared/types/meeting";

const route = useRoute();
const meetingStore = useMeetingStore();
const membersService = createLocalMembersService();

const selectedId = ref<string | null>(null);
const members = ref<MeetingMember[]>([]);
const errorMessage = ref("");
const draft = reactive(createDraft());

const messages = computed(() => getMessages(meetingStore.settings.value.locale).members);
const commonMessages = computed(() => getMessages(meetingStore.settings.value.locale).common);

onMounted(async () => {
  await meetingStore.ensureSettingsLoaded();
  await loadMembers();
  const memberId = typeof route.query.id === "string" ? route.query.id : null;

  if (memberId) {
    const member = members.value.find((item) => item.id === memberId);
    if (member) {
      selectedId.value = member.id;
      Object.assign(draft, createDraft(member));
      await syncWindowTitle(true);
      return;
    }
  }

  await syncWindowTitle(false);
});

function createDraft(member?: MeetingMember) {
  return {
    id: member?.id ?? crypto.randomUUID(),
    name: member?.name ?? "",
    department: member?.department ?? "",
    sortOrder: member?.sortOrder ?? 0,
    isRecorder: member?.isRecorder ?? false,
    createdAt: member?.createdAt ?? new Date().toISOString(),
    updatedAt: member?.updatedAt ?? new Date().toISOString(),
  };
}

async function loadMembers() {
  members.value = await membersService.listMembers();
}

function validateDraft() {
  if (!draft.name.trim()) {
    return messages.value.validationName;
  }

  if (!Number.isInteger(Number(draft.sortOrder))) {
    return messages.value.validationSortOrder;
  }

  return "";
}

async function syncWindowTitle(isEdit: boolean) {
  try {
    await getCurrentWindow().setTitle(isEdit ? messages.value.editorEditTitle : messages.value.editorNewTitle);
  } catch {
    // ignore
  }
}

async function saveMember() {
  const validation = validateDraft();
  if (validation) {
    errorMessage.value = validation;
    return;
  }

  const now = new Date().toISOString();
  const nextMember: MeetingMember = {
    id: draft.id,
    name: draft.name.trim(),
    department: draft.department.trim(),
    sortOrder: Number(draft.sortOrder),
    isRecorder: draft.isRecorder,
    createdAt: draft.createdAt,
    updatedAt: now,
  };

  await membersService.saveMember(nextMember);
  selectedId.value = nextMember.id;
  Object.assign(draft, { ...nextMember });
  errorMessage.value = "";
  await syncWindowTitle(true);
}

async function removeMember() {
  if (!selectedId.value) {
    return;
  }

  const confirmed = await confirm(formatMessage(messages.value.deleteConfirm, { name: draft.name.trim() }), {
    title: messages.value.deleteTitle,
    kind: "warning",
    okLabel: commonMessages.value.delete,
    cancelLabel: commonMessages.value.cancel,
  });
  if (!confirmed) {
    return;
  }

  await membersService.deleteMember(selectedId.value);
  selectedId.value = null;
  Object.assign(draft, createDraft());
  errorMessage.value = "";
  await syncWindowTitle(false);
}

function resetDraft() {
  selectedId.value = null;
  Object.assign(draft, createDraft());
  errorMessage.value = "";
  void syncWindowTitle(false);
}
</script>

<template>
  <section class="editor-window-shell">
    <article class="surface editor-window-card">
      <div class="section-heading">
        <h3>{{ selectedId ? messages.editorEditTitle : messages.editorNewTitle }}</h3>
      </div>

      <div class="field-grid">
        <div class="field">
          <label for="member-name">{{ messages.name }}</label>
          <input id="member-name" v-model="draft.name" :placeholder="messages.namePlaceholder" />
        </div>

        <div class="field">
          <label for="member-department">{{ messages.department }}</label>
          <input id="member-department" v-model="draft.department" :placeholder="messages.departmentPlaceholder" />
        </div>

        <div class="field">
          <label for="member-sort-order">{{ messages.sortOrder }}</label>
          <input
            id="member-sort-order"
            v-model="draft.sortOrder"
            type="number"
            step="1"
            :placeholder="messages.sortOrderPlaceholder"
          />
        </div>

        <div class="field-grid two-col">
          <label class="toggle-field">
            <input v-model="draft.isRecorder" type="checkbox" />
            <span>{{ messages.recorderSwitch }}</span>
          </label>
        </div>
      </div>

      <div v-if="errorMessage" class="note-block error-block">
        {{ errorMessage }}
      </div>

      <div class="button-row">
        <button class="primary-button" type="button" @click="saveMember">
          {{ messages.save }}
        </button>
        <button class="secondary-button" type="button" @click="resetDraft">
          {{ messages.reset }}
        </button>
        <button v-if="selectedId" class="text-button danger-text" type="button" @click="removeMember">
          {{ commonMessages.delete }}
        </button>
      </div>
    </article>
  </section>
</template>

// apps/desktop/src/features/members/views/MemberEditorView.tsx
import { confirm } from "@tauri-apps/plugin-dialog";
import { getCurrentWindow } from "@tauri-apps/api/window";
import { useEffect, useState } from "react";
import { useMeetingStore } from "@/features/meeting/stores/useMeetingStore";
import { formatMessage, getMessages } from "@/shared/i18n";
import { createLocalMembersService } from "@/shared/services/tauri/members";
import type { MeetingMember } from "@/shared/types/meeting";

const membersService = createLocalMembersService();

function createDraft(member?: MeetingMember): MeetingMember {
  return {
    id: member?.id ?? crypto.randomUUID(),
    name: member?.name ?? "",
    department: member?.department ?? "",
    sortOrder: member?.sortOrder ?? 0,
    isRecorder: member?.isRecorder ?? false,
    createdAt: member?.createdAt ?? new Date().toISOString(),
    updatedAt: member?.updatedAt ?? new Date().toISOString(),
  };
}

export default function MemberEditorView() {
  const meetingStore = useMeetingStore();
  const [selectedId, setSelectedId] = useState<string | null>(null);
  const [errorMessage, setErrorMessage] = useState("");
  const [draft, setDraft] = useState<MeetingMember>(() => createDraft());
  const messages = getMessages(meetingStore.settings.locale).members;
  const commonMessages = getMessages(meetingStore.settings.locale).common;

  useEffect(() => {
    void initialize();
  }, []);

  async function initialize() {
    await meetingStore.ensureSettingsLoaded();
    const loadedMembers = await membersService.listMembers();
    const memberId = new URLSearchParams(window.location.search).get("id");

    if (memberId) {
      const member = loadedMembers.find((item) => item.id === memberId);
      if (member) {
        setSelectedId(member.id);
        setDraft(createDraft(member));
        await syncWindowTitle(true);
        return;
      }
    }

    await syncWindowTitle(false);
  }

  function patchDraft(patch: Partial<MeetingMember>) {
    setDraft((current) => ({ ...current, ...patch }));
  }

  function validateDraft() {
    if (!draft.name.trim()) {
      return messages.validationName;
    }
    if (!Number.isInteger(Number(draft.sortOrder))) {
      return messages.validationSortOrder;
    }
    return "";
  }

  async function syncWindowTitle(isEdit: boolean) {
    try {
      await getCurrentWindow().setTitle(isEdit ? messages.editorEditTitle : messages.editorNewTitle);
    } catch {
      // ignore
    }
  }

  async function saveMember() {
    const validation = validateDraft();
    if (validation) {
      setErrorMessage(validation);
      return;
    }

    const now = new Date().toISOString();
    const nextMember: MeetingMember = {
      id: draft.id,
      name: draft.name.trim(),
      department: draft.department.trim(),
      sortOrder: Number(draft.sortOrder),
      isRecorder: draft.isRecorder,
      createdAt: draft.createdAt,
      updatedAt: now,
    };

    await membersService.saveMember(nextMember);
    setSelectedId(nextMember.id);
    setDraft({ ...nextMember });
    setErrorMessage("");
    await syncWindowTitle(true);
  }

  async function removeMember() {
    if (!selectedId) {
      return;
    }

    const confirmed = await confirm(formatMessage(messages.deleteConfirm, { name: draft.name.trim() }), {
      title: messages.deleteTitle,
      kind: "warning",
      okLabel: commonMessages.delete,
      cancelLabel: commonMessages.cancel,
    });
    if (!confirmed) {
      return;
    }

    await membersService.deleteMember(selectedId);
    resetDraft();
  }

  function resetDraft() {
    setSelectedId(null);
    setDraft(createDraft());
    setErrorMessage("");
    void syncWindowTitle(false);
  }

  return (
    <section className="editor-window-shell native-editor-window">
      <article className="surface editor-window-card native-editor-card">
        <div className="section-heading">
          <h3>{selectedId ? messages.editorEditTitle : messages.editorNewTitle}</h3>
        </div>

        <div className="native-editor-layout">
          <aside className="native-editor-aside">
            <strong>{messages.title}</strong>
            <p>{messages.copy}</p>
            <span>{selectedId ? messages.editorEditTitle : messages.editorNewTitle}</span>
          </aside>

          <div className="field-grid native-editor-form">
            <div className="field">
              <label htmlFor="member-name">{messages.name}</label>
              <input id="member-name" value={draft.name} onChange={(event) => patchDraft({ name: event.target.value })} placeholder={messages.namePlaceholder} />
            </div>
            <div className="field">
              <label htmlFor="member-department">{messages.department}</label>
              <input id="member-department" value={draft.department} onChange={(event) => patchDraft({ department: event.target.value })} placeholder={messages.departmentPlaceholder} />
            </div>
            <div className="field">
              <label htmlFor="member-sort-order">{messages.sortOrder}</label>
              <input id="member-sort-order" value={draft.sortOrder} onChange={(event) => patchDraft({ sortOrder: Number(event.target.value) })} type="number" step="1" placeholder={messages.sortOrderPlaceholder} />
            </div>
            <div className="field-grid two-col">
              <label className="toggle-field">
                <input checked={draft.isRecorder} onChange={(event) => patchDraft({ isRecorder: event.target.checked })} type="checkbox" />
                <span>{messages.recorderSwitch}</span>
              </label>
            </div>
          </div>
        </div>

        {errorMessage && <div className="note-block error-block">{errorMessage}</div>}

        <div className="button-row">
          <button className="primary-button" type="button" onClick={saveMember}>
            {messages.save}
          </button>
          <button className="secondary-button" type="button" onClick={resetDraft}>
            {messages.reset}
          </button>
          {selectedId && (
            <button className="text-button danger-text" type="button" onClick={removeMember}>
              {commonMessages.delete}
            </button>
          )}
        </div>
      </article>
    </section>
  );
}
